# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: MSKazemi.YazSes
PackageVersion: 2.33.0
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ProductCode: '{F3E8B8A4-1B6C-4F24-9BE8-9B7E58E9C4A2}_is1'
MinimumOSVersion: 10.0.19041.0
ReleaseDate: 2026-08-27
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/MSKazemi/yazses/releases/download/v2.33.0/YazSes-2.33.0-windows-x64.exe
    InstallerSha256: DE405A7A4FE9A1A48DBF38E284C9CF14040B7EEF16F78659743599B606A4366F
ManifestType: installer
ManifestVersion: 1.6.0
