"""The semantic layer of the contract: meaning must survive post-processing.

`contract/vectors/*.json` pins *parity* — every platform delivers the same string.
That is necessary and not sufficient. Parity vectors are generated by running the
shipped Python, so a desktop change can update the implementation, the generator and
the golden data together and make a meaning-destroying rule the cross-platform
consensus. Every vector stays green while every platform is wrong in the same way.

`contract/semantic/` is the independent anchor (ADR-MOB-008 §8, raised in the mobile
design review, issue #98). Its expectations are **hand-authored and never regenerated**:
they say what a human must receive, not what the code currently emits. Two checks that
a parity vector cannot make:

  1. an invariant — the delivered text must still read with the declared polarity,
     actor, time, quantity, unit, certainty, correction marker or assessment;
  2. a minimal pair — two utterances differing in exactly one consequential dimension
     must not collapse to the same delivered text. Each output can look perfectly
     plausible on its own while the distinction between them is gone.

Cases marked `known-gap` are invariants the shipped filter does NOT satisfy. They are
strict-xfail: the suite is green while the gap is documented, and the moment somebody
fixes the code it goes red asking for the case to be promoted to `holds`. A gap can be
recorded but not forgotten, and never silently blessed.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pytest

from yazses.commands.grammar import classify
from yazses.config import DisfluencyConfig
from yazses.postprocess.cleaner import clean_text
from yazses.postprocess.voice_punctuation import apply_voice_punctuation
from yazses.stt.filters.disfluency import filter_transcript

ROOT = Path(__file__).resolve().parent.parent
SEMANTIC_DIR = ROOT / "contract" / "semantic"

DIMENSIONS = json.loads((SEMANTIC_DIR / "dimensions.json").read_text(encoding="utf-8"))
INVARIANTS = json.loads((SEMANTIC_DIR / "invariants.json").read_text(encoding="utf-8"))
CASES: list[dict[str, Any]] = INVARIANTS["cases"]
BY_ID = {c["id"]: c for c in CASES}


# ── the portable extractor ────────────────────────────────────────────────────
#
# Deliberately tiny: apply patterns, read off a value. Any platform reimplements
# this in a few dozen lines, which is the point — the semantic layer must be as
# portable as the parity vectors it backstops.

def extract(dimension: str, text: str) -> str | set[str]:
    spec = DIMENSIONS["dimensions"][dimension]
    flags = 0 if DIMENSIONS["matching"]["case_sensitive"] else re.IGNORECASE

    def hit(value: dict[str, Any]) -> bool:
        return any(re.search(p, text, flags) for p in value["patterns"])

    if spec["kind"] == "scalar":
        for value in spec["values"]:
            if hit(value):
                return str(value["value"])
        return str(spec["default"])
    return {str(v["value"]) for v in spec["values"] if hit(v)}


def deliver(case: dict[str, Any]) -> str:
    """The DICTATE delivered-text chain, exactly as the daemon runs it, minus injection."""
    options = dict(case.get("options") or {})
    voice_punctuation = options.pop("voice_punctuation", False)
    text = clean_text(case["input"])
    text = filter_transcript(text, DisfluencyConfig(**options)).text
    if voice_punctuation:
        text = apply_voice_punctuation(text)
    return text


def _positions(dimension: str, value: str, text: str) -> list[int]:
    """Every character offset in *text* where *value* is read for *dimension*.

    Uses the dimension's own extraction patterns, so a relation is anchored to
    exactly what `must_preserve` reads — not to a second, looser search.
    """
    spec = DIMENSIONS["dimensions"][dimension]
    flags = re.IGNORECASE if spec.get("ignore_case", True) else 0
    for entry in spec["values"]:
        if str(entry["value"]) != str(value):
            continue
        return sorted(
            m.start() for pattern in entry["patterns"] for m in re.finditer(pattern, text, flags)
        )
    return []


def _check_relations(case: dict[str, Any], actual: str) -> list[str]:
    """Assert ORDER between values, which `must_preserve` cannot express (#163).

    `quantity` is a set dimension and `must_preserve` is a subset assertion, so
    "give him fifty, sorry, fifteen milligrams" and its inversion both extract
    {15, 50} with a correction marker and satisfy the invariant identically —
    while meaning the opposite. The flagship case the semantic layer exists to
    protect was the one it did not actually pin.

    A relation says *which value supersedes*: `supersedes` requires that the
    winning value appears after the superseded one, so the inverted sentence
    fails. Deliberately positional rather than semantic — the contract's own rule
    is that it pins delivered text, not meaning.
    """
    failures = []
    for relation in case.get("must_preserve_relation") or []:
        dimension = relation["dimension"]
        kind = relation["relation"]
        winner, loser = str(relation["value"]), str(relation["over"])
        winner_at = _positions(dimension, winner, actual)
        loser_at = _positions(dimension, loser, actual)
        if not winner_at:
            failures.append(f"{dimension}: {winner!r} is absent, so it cannot {kind} {loser!r}")
            continue
        if not loser_at:
            continue      # the superseded value is gone entirely — nothing to confuse
        if kind == "supersedes":
            if not (max(winner_at) > min(loser_at)):
                failures.append(
                    f"{dimension}: {winner!r} must supersede {loser!r}, but it does not "
                    f"appear after it (winner at {winner_at}, superseded at {loser_at}) — "
                    f"this reads as the opposite instruction"
                )
        else:
            failures.append(f"unknown relation kind {kind!r}")
    return failures


def _check_invariants(case: dict[str, Any], actual: str) -> list[str]:
    """Return a human-readable failure per violated invariant (empty == all held)."""
    failures = []
    for dimension, required in (case.get("must_preserve") or {}).items():
        reading = extract(dimension, actual)
        if isinstance(reading, set):
            missing = set(required) - reading
            if missing:
                failures.append(
                    f"{dimension}: lost {sorted(missing)} "
                    f"(required {sorted(required)}, output reads {sorted(reading)})"
                )
        elif reading != required:
            failures.append(f"{dimension}: required {required!r}, output reads {reading!r}")
    for dimension, forbidden in (case.get("must_not_acquire") or {}).items():
        reading = extract(dimension, actual)
        acquired = (set(forbidden) & reading) if isinstance(reading, set) else (
            {reading} if reading in forbidden else set()
        )
        if acquired:
            failures.append(f"{dimension}: output wrongly acquired {sorted(acquired)}")
    failures += _check_relations(case, actual)
    return failures


def _mark(case: dict[str, Any]) -> list[Any]:
    if case["status"] != "known-gap":
        return []
    return [pytest.mark.xfail(
        strict=True,
        reason=(
            f"known gap ({case['gap']['cause']}) — {case['gap']['issue']}. "
            f"If this now passes, the code was fixed: promote the case to status 'holds'."
        ),
    )]


PARAMS = [pytest.param(c, marks=_mark(c), id=c["id"]) for c in CASES]


@pytest.mark.parametrize("case", PARAMS)
def test_meaning_survives_post_processing(case):
    actual = deliver(case)
    violations = _check_invariants(case, actual)
    assert actual == case["expected"] and not violations, (
        f"\nsemantic invariant '{case['id']}' does not hold."
        f"\n  {case['description']}"
        f"\n  input:    {case['input']!r}"
        f"\n  required: {case['expected']!r}"
        f"\n  actual:   {actual!r}"
        + ("".join(f"\n  violated  {v}" for v in violations) if violations else "")
        + "\n\nThis file is NOT regenerated from the implementation. If the code and this"
        "\nfile disagree, the code is what changes — or the case moves to status"
        "\n'known-gap' with an issue link, in the same PR, reviewed as a behaviour change."
    )


@pytest.mark.parametrize(
    "case", [c for c in CASES if c.get("must_classify_as")],
    ids=[c["id"] for c in CASES if c.get("must_classify_as")],
)
def test_utterance_is_classified_as_declared(case):
    """A sentence about a patient must be typed, never executed."""
    actual = classify(case["input"]).intent.value
    assert actual == case["must_classify_as"], (
        f"{case['id']}: {case['input']!r} classified as {actual!r}, "
        f"expected {case['must_classify_as']!r} — a misclassified clinical sentence "
        f"is not typed at all, it fires an editor command."
    )


PAIRS = [c for c in CASES if c.get("minimal_pair")]
PAIR_PARAMS = [
    pytest.param(
        c,
        marks=(_mark(c) or _mark(BY_ID[c["minimal_pair"]["partner"]])),
        id=f"{c['id']}~{c['minimal_pair']['partner']}",
    )
    for c in PAIRS
]


@pytest.mark.parametrize("case", PAIR_PARAMS)
def test_minimal_pair_does_not_collapse(case):
    """Two utterances differing in one consequential dimension must stay different."""
    pair = case["minimal_pair"]
    partner = BY_ID[pair["partner"]]
    dimension = pair["differs_in"]
    mine, theirs = deliver(case), deliver(partner)
    assert mine != theirs, (
        f"\n{case['id']} and {partner['id']} both deliver {mine!r}."
        f"\nThey differ in {dimension} — post-processing erased the distinction."
        f"\n  {case['input']!r}"
        f"\n  {partner['input']!r}"
        f"\nEach output alone looks plausible; together they prove meaning was lost."
    )
    assert extract(dimension, mine) != extract(dimension, theirs), (
        f"{case['id']} and {partner['id']} deliver different text but both now read "
        f"{dimension}={extract(dimension, mine)!r} — the distinction is gone even though "
        f"the strings differ."
    )


# ── the layer's own integrity ─────────────────────────────────────────────────

def test_semantic_layer_is_not_reachable_by_the_generator():
    """The whole point: this layer cannot be regenerated from the implementation.

    If the vector generator ever learns to write here, a bad desktop change could
    update the code and its own oracle in one step — which is what the parity layer
    already permits and what this layer exists to prevent.
    """
    source = (ROOT / "scripts" / "gen-contract-vectors.py").read_text(encoding="utf-8")
    assert "semantic" not in source, (
        "scripts/gen-contract-vectors.py mentions 'semantic'. The semantic layer must "
        "stay hand-authored — a generator that can write it is not an independent anchor."
    )


def test_every_known_gap_reproduces_exactly_as_documented():
    """A gap must be recorded truthfully, and stay recorded truthfully."""
    for case in CASES:
        if case["status"] != "known-gap":
            continue
        actual = deliver(case)
        assert actual == case["gap"]["actual"], (
            f"{case['id']}: the documented gap says the implementation delivers "
            f"{case['gap']['actual']!r}, but it delivers {actual!r}. Behaviour moved — "
            f"re-read the case and either promote it to 'holds' or update the record."
        )


def test_every_known_gap_carries_an_issue():
    for case in CASES:
        if case["status"] == "known-gap":
            assert case["gap"]["issue"].startswith("https://"), (
                f"{case['id']}: a known gap without a tracked issue is a gap nobody "
                f"will fix — it is indistinguishable from intended behaviour."
            )
            assert case["gap"]["cause"].strip(), f"{case['id']}: gap has no stated cause"


def test_cases_are_well_formed_and_uniquely_identified():
    ids = [c["id"] for c in CASES]
    assert len(ids) == len(set(ids)), "duplicate case id"
    for case in CASES:
        assert case["id"] == case["id"].lower(), f"case id must be lower-case: {case['id']}"
        assert case["description"].strip(), f"{case['id']} has no description"
        assert case["status"] in {"holds", "known-gap"}, f"{case['id']}: bad status"
        assert case.get("must_preserve"), (
            f"{case['id']} declares no conserved dimension — then it is a parity vector, "
            f"and belongs in contract/vectors/ instead"
        )
        for dimension in {**case.get("must_preserve", {}), **case.get("must_not_acquire", {})}:
            assert dimension in DIMENSIONS["dimensions"], (
                f"{case['id']} cites unknown dimension {dimension!r}"
            )


def test_minimal_pairs_are_symmetric():
    """A one-sided pair silently stops being checked from the other end."""
    for case in PAIRS:
        pair = case["minimal_pair"]
        partner = BY_ID.get(pair["partner"])
        assert partner, f"{case['id']} points at missing partner {pair['partner']!r}"
        back = partner.get("minimal_pair")
        assert back and back["partner"] == case["id"], (
            f"{case['id']} pairs with {partner['id']}, which does not pair back"
        )
        assert back["differs_in"] == pair["differs_in"], (
            f"{case['id']} and {partner['id']} disagree on which dimension they differ in"
        )


def test_declared_contract_version_matches():
    version = (ROOT / "contract" / "VERSION").read_text(encoding="utf-8").strip()
    for doc, name in ((DIMENSIONS, "dimensions.json"), (INVARIANTS, "invariants.json")):
        assert doc["contract_version"] == version, (
            f"contract/semantic/{name} declares {doc['contract_version']}, "
            f"contract/VERSION says {version}"
        )
        assert doc["generated"] is False, f"{name} must declare generated=false"


def test_every_dimension_is_exercised_by_a_case():
    """An unused dimension is untested lexicon that will rot."""
    cited = set()
    for case in CASES:
        cited |= set(case.get("must_preserve") or {})
        cited |= set(case.get("must_not_acquire") or {})
    unused = set(DIMENSIONS["dimensions"]) - cited
    assert not unused, f"dimensions defined but never used by a case: {sorted(unused)}"


def test_a_relation_rejects_the_inversion_a_subset_check_accepts():
    """The whole point of `must_preserve_relation` (#163).

    "give him fifty, sorry, fifteen milligrams" and its inversion extract the
    same quantity set {15, 50} with the same correction marker, so the flagship
    case's `must_preserve` is satisfied by BOTH — while they mean the opposite.
    This pins that the relation is what separates them, and that removing it
    brings the hole back.
    """
    flagship = next(
        c for c in INVARIANTS["cases"] if c["id"] == "self-correction-keeps-corrected-dose"
    )
    inverted = "give him fifteen, sorry, fifty milligrams"

    without_relation = {k: v for k, v in flagship.items() if k != "must_preserve_relation"}
    assert not _check_invariants(without_relation, inverted), (
        "the subset assertion is expected to accept the inversion — that is the gap"
    )
    failures = _check_invariants(flagship, inverted)
    assert failures, "must_preserve_relation must reject the inverted instruction"
    assert "supersede" in failures[0]


def test_every_relation_names_a_dimension_that_exists():
    for case in INVARIANTS["cases"]:
        for relation in case.get("must_preserve_relation") or []:
            assert relation["dimension"] in DIMENSIONS["dimensions"], (
                f"{case['id']} relates an unknown dimension {relation['dimension']!r}"
            )
            assert relation["relation"] == "supersedes", "only `supersedes` is implemented"
            assert relation.get("why"), f"{case['id']}: a relation must say why it exists"


def test_the_minimal_pair_for_the_flagship_case_is_present():
    """A relation without its counter-example is an assertion nobody has tested."""
    ids = {c["id"] for c in INVARIANTS["cases"]}
    assert "self-correction-inverted-dose-is-a-different-instruction" in ids
