"""The example config three packagers install told users to undo a bug fix.

`examples/` holds two neutral starting templates. `config.toml` is **generated** from the
dataclass defaults by `scripts/gen-example-config.py` and stale-checked by
`test_example_config.py`; its header says so, and says not to trust a value the code
disagrees with. `config.example.toml` is hand-written, generated by nothing, and is the
one `scripts/build-deb.sh`, `debian/rules` and `packaging/arch/PKGBUILD` all install to
`/usr/share/yazses/`. The correct file ships nowhere.

It had drifted, in the direction that costs a user something:

* `[stt] model = "tiny.en"` while the shipped default is `base.en` — copying the file a
  user is told to copy silently downgrades transcription accuracy. `base.en` has been the
  default since the initial commit, so this was never right rather than newly stale.
* `[audio] max_record_seconds = 90` while the default is `300`. `a1be5e3` raised that
  ceiling *because 90 was cutting long dictations off*, and the example still handed
  people the value that commit removed — copying it re-introduces the fixed bug.

Two guards already sweep `examples/`, and neither could see this. `test_app_example_configs`
rejects a key that does not **exist**; `test_no_example_config_offers_a_knob_that_does_nothing`
rejects a key nothing **reads**. A live, read, correctly-spelled key holding the wrong
*value* passes both perfectly. Values were the unchecked axis.

**Scope, and why it is not every example.** An app profile deviating from the defaults is
the entire point of an app profile — `config.terminal.toml` sets `backend = "type"`
because clipboard-paste does not work in a terminal. Across all 18 examples there are 86
deviations, 36 of them unannotated; holding those to the defaults would be wrong, and
annotating them would mean inventing rationales for contributor-authored files. What is
*not* a matter of taste is a file this project puts on a user's disk as the starting
point. So the region is derived from the packaging scripts themselves: whatever they
install is what this guard checks. Point a packager at a different example tomorrow and
it is covered without editing this file.

The README's single ``toml`` block is held to the same rule for the same reason, and it
had drifted further than the file: under the heading *"Essential settings:"* it showed
``model = "small.en"``, ``max_record_seconds = 90`` and ``vad_threshold = 0.0008`` against
a shipped default of ``0.01`` -- a gate twelve times more sensitive, handed to every
reader of the front page, predisposing them to the spurious-transcript problem
``yazses mic-level`` exists to fix. Like ``tiny.en``, it was never the default: both have
been what they are since the initial commit.
"""
from __future__ import annotations

import pathlib
import re
import tomllib

import pytest

from yazses.config import Config

ROOT = pathlib.Path(__file__).resolve().parents[1]

#: The packaging scripts that can put an example config on a user's disk. Each is read
#: for the examples it installs; the *paths* are never written down here, only the
#: installers. A missing file fails rather than silently shrinking the swept region.
_PACKAGERS = (
    "scripts/build-deb.sh",
    "debian/rules",
    "packaging/arch/PKGBUILD",
)

_INSTALLED = re.compile(r"examples/(config[\w.-]*\.toml)")


def _shipped() -> dict[str, list[str]]:
    """Example filename -> the packaging scripts that install it."""
    out: dict[str, list[str]] = {}
    for rel in _PACKAGERS:
        path = ROOT / rel
        assert path.exists(), (
            f"{rel} is named as a packaging script but does not exist; this guard would "
            "quietly stop checking whatever it used to ship"
        )
        for name in _INSTALLED.findall(path.read_text(encoding="utf-8")):
            out.setdefault(name, []).append(rel)
    return out


def test_every_packager_ships_an_example_config():
    """Non-vacuity, per packager rather than in total.

    A guard that iterates is green over an empty set, and a *partly* empty set is the
    sneakier version: two packagers matched and one silently contributing nothing reads
    as full coverage.
    """
    shipped = _shipped()
    assert shipped, "no packaging script installs any example config — the regex is broken"
    covered = {p for paths in shipped.values() for p in paths}
    missing = sorted(set(_PACKAGERS) - covered)
    assert not missing, f"{missing} install no example config; the sweep does not cover them"


@pytest.mark.parametrize("name", sorted(_shipped()))
def test_a_shipped_example_states_no_value_the_code_disagrees_with(name):
    """Copying what we install must not change how YazSes behaves."""
    cfg = Config()
    path = ROOT / "examples" / name
    assert path.exists(), f"{name} is installed by {_shipped()[name]} but is not in examples/"

    data = tomllib.loads(path.read_text(encoding="utf-8"))
    assert data, f"{name} is empty, so checking its values proves nothing"

    problems: list[str] = []
    checked = 0
    for section, keys in data.items():
        live = getattr(cfg, section, None)
        if live is None:
            problems.append(f"[{section}] is not a config section")
            continue
        for key, value in keys.items():
            if not hasattr(live, key):
                problems.append(f"[{section}] {key} is not a config key")
                continue
            checked += 1
            default = getattr(live, key)
            if default != value:
                problems.append(
                    f"[{section}] {key} = {value!r}, but the shipped default is "
                    f"{default!r} — copying this file changes behaviour silently"
                )

    assert checked >= 5, f"only {checked} keys checked in {name}; the parse is wrong"
    assert not problems, (
        f"{name} is installed to /usr/share/yazses/ by {', '.join(_shipped()[name])} and "
        "is what users are told to copy:\n  " + "\n  ".join(problems)
    )


def _readme_toml_blocks() -> list[str]:
    """Every ```toml fenced block in the README."""
    text = (ROOT / "README.md").read_text(encoding="utf-8")
    return re.findall(r"```toml\n(.*?)```", text, re.S)


def test_the_readme_shows_exactly_one_config_block():
    """If a second block appears, this guard has to be told what it is.

    Failing here is the point: a new block is either another config we show everyone --
    and must be checked -- or an illustrative fragment that must be excluded on purpose.
    Silently checking only the first would be the worse of the two.
    """
    blocks = _readme_toml_blocks()
    assert len(blocks) == 1, (
        f"README.md has {len(blocks)} toml blocks; this guard checks the config block "
        "and cannot tell which is which"
    )


def test_the_readme_config_block_states_no_value_the_code_disagrees_with():
    """The front page is the most-copied config surface in the project."""
    cfg = Config()
    data = tomllib.loads(_readme_toml_blocks()[0])
    assert data, "the README config block did not parse into anything"

    problems: list[str] = []
    checked = 0
    for section, keys in data.items():
        live = getattr(cfg, section, None)
        if live is None:
            problems.append(f"[{section}] is not a config section")
            continue
        for key, value in keys.items():
            if not hasattr(live, key):
                problems.append(f"[{section}] {key} is not a config key")
                continue
            checked += 1
            default = getattr(live, key)
            if default != value:
                problems.append(
                    f"[{section}] {key} = {value!r}, but the shipped default is "
                    f"{default!r} -- the README calls these \"essential settings\", so a "
                    "reader copying the block changes behaviour without meaning to"
                )

    assert checked >= 8, f"only {checked} keys checked; the README block parse is wrong"
    assert not problems, "README.md's config block:\n  " + "\n  ".join(problems)


def _translated_pages() -> dict[str, str]:
    """Translated landing page -> its single toml block, for pages that have one."""
    out: dict[str, str] = {}
    for path in sorted((ROOT / "docs").rglob("index.md")):
        blocks = re.findall(r"```toml\n(.*?)```", path.read_text(encoding="utf-8"), re.S)
        if len(blocks) == 1:
            out[path.relative_to(ROOT).as_posix()] = blocks[0]
    return out


def test_the_translations_were_found():
    pages = _translated_pages()
    assert len(pages) >= 3, f"only {len(pages)} translated config blocks found: {list(pages)}"


@pytest.mark.parametrize("page", sorted(_translated_pages()))
def test_a_translated_config_block_matches_english_or_declares_its_language(page):
    """A translation may localise its prose; drifting its *values* is a different thing.

    `docs/ru/index.md` and `docs/hi/index.md` carried a block that was byte-identical to
    each other and stale against the README: `model = "small.en"`, `key = "space"`,
    `max_record_seconds = 90`, `vad_threshold = 0.0008`, and `xdotool` offered as an
    injection backend the README says is not a token. Every comment in them was in
    English, so they were not translated content at all -- they were copies of an older
    README that nothing kept in step.

    `docs/zh-CN/index.md` is the legitimate exception and shows why the rule cannot
    simply be "match English": a Chinese setup *must* set `[stt] language = "zh"` and a
    non-`.en` model, or the page would be documenting a configuration that transcribes
    Chinese speech as English-looking nonsense. So the test is match-English **or**
    declare a language -- a page that deviates has to say what it is deviating for.
    """
    block = _translated_pages()[page]
    english = _readme_toml_blocks()[0]
    if block == english:
        return
    data = tomllib.loads(block)
    declared = data.get("stt", {}).get("language", "")
    # Non-default, not merely present: a page that deviates *and* declares the shipped
    # default language is not documenting another language's setup, it has drifted.
    # `language = "en"` would otherwise satisfy a bare truthiness check.
    assert declared and declared != Config().stt.language, (
        f"{page}'s config block differs from the README's and declares "
        f"`[stt] language = {declared!r}`. Either it drifted -- copy the README block --"
        " or it is a language-specific setup, which must say which language it is for."
    )
