"""What `yazses features` prints in DOWNLOAD has to include the model, not just the wheel.

The catalogue priced **Read-Back Loop** at `~12 MB`. `src/yazses/tts/download.py`, whose
job is to fetch what that feature runs on, opens with *"one-time (~340 MB)"*. Both
numbers were committed to this repository; nothing compared them, so the column read
29x under and `LOUD_DOWNLOAD_MB` -- the constant whose comment names the failure "I
asked for a small feature and it filled my disk" -- could never fire on the one feature
that fills a disk. `recimport`/`meeting`/`diarize` were understated the same way (18 MB
against 45 MB of sherpa models), and `gaze` by 3.7 MB.

The reason it survived is structural: `feature_sizes.json` is generated by resolving
**pip** closures, and a model file is not a package. So the fix cannot be a bigger
generated table, and the guard cannot be a list of the features that were wrong on the
day it was written -- that list says nothing about the fifth downloader. Both sides are
derived from the tree instead: every ``download.py`` under ``src/yazses`` must be priced,
and where the module states its own size in its docstring, the price must be that size.
"""
from __future__ import annotations

import ast
import pathlib
import re

import pytest

from yazses.system import depsize
from yazses.system.depsize import _MODEL_FETCHERS

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"

#: A size a module states about itself, e.g. "one-time (~340 MB)" or "~3.7 MB TFLite".
_STATED_MB = re.compile(r"~\s*([\d.]+)\s*MB")

#: Non-vacuity. Four downloaders exist today; a guard that iterates an empty set is
#: green on a tree with none of them, which is the shape that has bitten this repo.
_MIN_FETCHERS = 4


def _download_modules() -> dict[str, pathlib.Path]:
    """Every ``download.py`` in the package, keyed the way the table keys it."""
    return {
        str(p.relative_to(SRC)): p
        for p in (SRC / "yazses").rglob("download.py")
    }


def _stated_mb(path: pathlib.Path) -> float | None:
    """The largest size the module's own docstring claims, or ``None``."""
    doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
    found = [float(m) for m in _STATED_MB.findall(doc)]
    return max(found) if found else None


# --- the two sides must be the same set ---------------------------------------


def test_there_are_download_modules_to_check():
    assert len(_download_modules()) >= _MIN_FETCHERS


def test_every_downloader_in_the_tree_is_priced():
    """A new model downloader fails this until someone decides what it costs."""
    missing = sorted(set(_download_modules()) - set(_MODEL_FETCHERS))
    assert not missing, (
        f"these modules fetch model files that no feature is priced for: {missing} -- "
        "add them to depsize._MODEL_FETCHERS with the size and the slugs that pay for it"
    )


def test_nothing_is_priced_that_does_not_exist():
    stale = sorted(set(_MODEL_FETCHERS) - set(_download_modules()))
    assert not stale, f"priced modules that are gone: {stale}"


# --- the comparison that was missing -------------------------------------------


@pytest.mark.parametrize("rel", sorted(_MODEL_FETCHERS))
def test_the_price_matches_what_the_module_says_about_itself(rel):
    """The docstring and the column are the two facts that disagreed. Hold them equal."""
    priced, _ = _MODEL_FETCHERS[rel]
    stated = _stated_mb(SRC / rel)
    if stated is None:
        assert priced == 0.0, (
            f"{rel} is priced at {priced} MB but says nothing about its own size -- "
            "state it in the docstring so the two can be checked against each other"
        )
    else:
        assert priced == pytest.approx(stated), (
            f"{rel} says ~{stated} MB in its docstring and is priced at {priced} MB"
        )


def test_the_read_back_voice_is_the_case_that_forced_this():
    """Named explicitly: it is the regression, and 340 MB is not a rounding argument."""
    assert depsize.model_download_mb("read-back") == pytest.approx(340.0)


def test_every_priced_slug_is_a_real_capability():
    """A renamed slug would leave the price attached to nothing, silently."""
    from yazses.system.features import toggleable_slugs

    known = set(toggleable_slugs())
    priced = {slug for _, slugs in _MODEL_FETCHERS.values() for slug in slugs}
    assert priced <= known, f"priced slugs that no longer exist: {sorted(priced - known)}"


def test_a_downloader_may_serve_more_than_one_slug():
    """The sherpa models are one download and three capabilities; pricing is per slug."""
    for slug in ("recimport", "meeting", "diarize"):
        assert depsize.model_download_mb(slug) == pytest.approx(45.0)


# --- what the user is actually shown -------------------------------------------


def test_the_catalogue_column_includes_the_model():
    label = depsize.catalogue_size_label("read-back", has_pip_deps=True)
    assert label == "~352 MB", label


def test_the_column_is_not_just_the_wheels():
    assert depsize.catalogue_size_label("read-back", has_pip_deps=True) != depsize.format_mb(
        depsize.full_download_mb("read-back")
    )


def test_a_feature_with_no_model_is_unchanged():
    """The fix must not inflate the 130-odd capabilities that fetch no model."""
    for slug in ("cocktail", "chinese-script", "overlay"):
        assert depsize.catalogue_size_label(slug, has_pip_deps=True) == depsize.format_mb(
            depsize.full_download_mb(slug)
        )


def test_a_model_is_priced_even_when_the_feature_has_no_pip_deps():
    """`has_pip_deps=False` used to return early, which would hide a pure-model cost."""
    assert depsize.catalogue_size_label("gaze", has_pip_deps=False) == "~3.7 MB"


def test_the_download_note_names_the_model_and_when_it_arrives():
    note = depsize.download_note("read-back", None)
    assert "~12 MB (7 packages)" in note
    assert "~340 MB of model files on first use" in note


def test_the_note_still_quotes_the_model_when_the_packages_are_installed():
    """The early return said "nothing to download" to a user about to fetch 340 MB."""
    note = depsize.download_note("read-back", [])
    assert "~340 MB" in note
    assert "package" not in note


def test_a_feature_with_neither_says_nothing():
    assert depsize.download_note("nosuchfeature", None) == ""


def test_first_use_is_packages_plus_model():
    assert depsize.first_use_mb("read-back") == pytest.approx(
        depsize.full_download_mb("read-back") + 340.0
    )


def test_first_use_is_none_only_when_there_is_nothing_to_say():
    assert depsize.first_use_mb("nosuchfeature") is None


# --- the guard that could never fire -------------------------------------------


def test_read_back_now_trips_the_loud_threshold():
    assert depsize.is_a_large_download("read-back", None) is True


def test_it_trips_it_on_the_model_alone():
    """Every package already installed, 340 MB still to come: that is still loud."""
    assert depsize.is_a_large_download("read-back", []) is True


def test_a_genuinely_small_feature_is_still_quiet():
    assert depsize.is_a_large_download("chinese-script", None) is False
    assert depsize.is_a_large_download("gaze", None) is False


# --- the sentence the user reads ------------------------------------------------


def test_the_catalogue_legend_says_model_files_are_counted():
    """A column that silently changed meaning is a second wrong number, not a fix."""
    src = (SRC / "yazses" / "cli.py").read_text(encoding="utf-8")
    flowed = " ".join(src.split())
    assert "DOWNLOAD = what a fresh install fetches in total" in flowed
    assert "model files the first time it runs" in flowed
