"""What `yazses features` prints in DOWNLOAD has to include the model, not just the wheel.

The catalogue priced **Read-Back Loop** at `~12 MB`. `src/yazses/tts/download.py`, whose
job is to fetch what that feature runs on, opens with *"one-time (~340 MB)"*. Both
numbers were committed to this repository; nothing compared them, so the column read
29x under and `LOUD_DOWNLOAD_MB` -- the constant whose comment names the failure "I
asked for a small feature and it filled my disk" -- could never fire on the one feature
that fills a disk. `recimport`/`meeting`/`diarize` were understated the same way (18 MB
against 45 MB of sherpa models), and `gaze` by 3.7 MB.

The reason it survived is structural: `feature_sizes.json` is generated by resolving
**pip** closures, and a model file is not a package. So the fix cannot be a bigger
generated table, and the guard cannot be a list of the features that were wrong on the
day it was written -- that list says nothing about the fifth downloader. Both sides are
derived from the tree instead: every ``download.py`` under ``src/yazses`` must be priced,
and where the module states its own size in its docstring, the price must be that size.

**2026-08-20 -- the same defect came back through this file's own blind spot.**
Deriving from ``download.py`` was still a hand-picked region: it is a *filename*, not the
behaviour. The two alternative STT engines fetch their weights through their own library
at first use, so neither owns a ``download.py``, and `yazses features` advertised
``stt-parakeet`` at **~4.0 MB** -- the `onnx-asr` wheel -- while `docs/models.md` said
"~600 MB model" in a table two files away. Exactly the read-back shape, 150x this time.

The complete classification already existed in
`tests/test_model_cache_first.py::_LOADERS`, which names ``stt/parakeet.py``. Two lists
of model fetchers, in two test files, and nothing compared them. So the derivation below
now covers both routes -- a ``download.py``, or a call to a hub loader entry point -- and
`test_the_two_lists_of_model_fetchers_agree` holds this file and that one to the same set.
"""
from __future__ import annotations

import ast
import pathlib
import re

import pytest

from yazses.system import depsize, features
from yazses.system.depsize import _MODEL_FETCHERS

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"

#: A size a module states about itself, e.g. "one-time (~340 MB)" or "~3.7 MB TFLite".
_STATED_MB = re.compile(r"~\s*([\d.]+)\s*MB")

#: Non-vacuity. Four downloaders exist today; a guard that iterates an empty set is
#: green on a tree with none of them, which is the shape that has bitten this repo.
_MIN_FETCHERS = 4


def _download_modules() -> dict[str, pathlib.Path]:
    """Every ``download.py`` in the package, keyed the way the table keys it."""
    return {
        # `.as_posix()`, never `str()`: on Windows `str()` yields
        # `yazses\\stt\\parakeet.py`, which matches none of the `yazses/...` keys
        # this file compares against -- so four tests failed there and nowhere
        # else, reading like a missing module rather than a separator.
        p.relative_to(SRC).as_posix(): p
        for p in (SRC / "yazses").rglob("download.py")
    }


def _stated_mb(path: pathlib.Path) -> float | None:
    """The largest size the module's own docstring claims, or ``None``."""
    doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
    found = [float(m) for m in _STATED_MB.findall(doc)]
    return max(found) if found else None


#: Entry points that pull a pretrained model down from the Hugging Face hub. Shared
#: with `tests/test_model_cache_first.py`, which asks a different question about the
#: same set of modules -- do they load cache-first -- and used to disagree about who
#: was in it. `MoonshineOnnxModel` is a class call rather than a named loader, which
#: is precisely why the cache-first guard had not noticed that `stt/moonshine.py`
#: fetched a model at all.
HUB_LOADERS = frozenset(
    {"from_hparams", "from_pretrained", "load_model", "snapshot_download",
     "MoonshineOnnxModel"}
)

#: Four hub fetchers exist today, alongside four `download.py` modules.
_MIN_HUB_FETCHERS = 4


def hub_fetching_modules() -> dict[str, set[str]]:
    """Every module under ``src/yazses`` that fetches a model from the hub.

    Keyed like `_MODEL_FETCHERS` (``yazses/...``), valued by which entry points it
    calls. Derived from the syntax tree rather than from a list, because a list of the
    fetchers that existed when it was written is the defect this file is about.
    """
    found: dict[str, set[str]] = {}
    for path in sorted((SRC / "yazses").rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        hits = {
            name
            for node in ast.walk(tree)
            if isinstance(node, ast.Call)
            for name in (getattr(node.func, "attr", None) or getattr(node.func, "id", None),)
            if name in HUB_LOADERS
        }
        if hits:
            found[path.relative_to(SRC).as_posix()] = hits
    return found


def model_fetching_modules() -> set[str]:
    """Both routes to a model file: a `download.py`, or a hub loader call."""
    return set(_download_modules()) | set(hub_fetching_modules())


# --- the classification is complete -------------------------------------------


def test_there_are_hub_fetchers_to_check():
    """A guard that iterates is green on an empty collection.

    The count alone cannot carry this. `_MIN_HUB_FETCHERS` is *itself* the assertion, so
    a walk that stopped finding anything is repaired by lowering the number -- the check
    can never fail in a way that survives someone editing it. Naming the modules is not
    circular: they are found by walking the tree, and a module that drops out of the walk
    fails here whatever the floor says.
    """
    found = hub_fetching_modules()
    assert len(found) >= _MIN_HUB_FETCHERS, found
    for known in ("yazses/stt/parakeet.py", "yazses/stt/moonshine.py",
                  "yazses/voiceprint/ecapa.py"):
        assert known in found, f"{known} fetches a model but the AST walk missed it: {found}"


def test_a_model_fetcher_is_reported_as_one():
    """`fetches_a_model` is what the label, the note and the threshold all branch on.

    Mutating it to a flat `False` left every test green: each caller was checked only on
    features that fetch nothing, so the answer they all agree on was the uninteresting
    one. Pin both sides of the predicate.
    """
    assert depsize.fetches_a_model("stt-parakeet")
    assert depsize.fetches_a_model("stt-moonshine")  # size unknown still counts
    assert depsize.fetches_a_model("cocktail")
    assert not depsize.fetches_a_model("chinese-script")
    assert not depsize.fetches_a_model("overlay")


def test_an_unquantified_model_is_flagged_not_hidden():
    """A number we cannot compute must not read as a number we did compute.

    `stt-moonshine` fetches weights of an unestablished size, so its wheel total is a
    floor and is shown as `~N MB+`; the note says so in words, and the threshold treats
    it as large, because the one thing that cannot be done with an unweighable download
    is weigh it.
    """
    label = depsize.catalogue_size_label("stt-moonshine", has_pip_deps=True)
    assert label.endswith("+"), label
    assert "model" in depsize.download_note("stt-moonshine", ["moonshine_onnx"])
    assert depsize.is_a_large_download("stt-moonshine", ["moonshine_onnx"])
    # ...and a feature with no model keeps a plain, unqualified figure.
    assert not depsize.catalogue_size_label("overlay", has_pip_deps=True).endswith("+")


def test_every_priced_model_reaches_a_real_feature():
    """A price attached to no feature is a price nobody is ever shown.

    Dropping `stt-moonshine` from its slug tuple left the table looking complete while
    the catalogue quietly went back to quoting the wheel alone.
    """
    known = {d.slug for d in features._registry()}
    for rel, (_, slugs) in _MODEL_FETCHERS.items():
        for slug in slugs:
            assert slug in known, f"{rel} is priced against unknown feature {slug!r}"


def test_every_model_fetching_module_is_priced():
    """Not just every `download.py` -- every module that ends up with model bytes.

    `stt/parakeet.py` is the case that forced this: it fetched ~600 MB through
    `onnx_asr.load_model` and was priced at its 4 MB wheel, because the previous
    version of this guard only knew about files called `download.py`.
    """
    unpriced = sorted(model_fetching_modules() - set(_MODEL_FETCHERS))
    assert not unpriced, (
        f"these fetch model files and `depsize._MODEL_FETCHERS` does not price them: "
        f"{unpriced}. Give each a size, or `None` if no figure is established -- but "
        "not silence, which is how a 600 MB engine advertised 4 MB."
    )


def test_the_two_lists_of_model_fetchers_agree():
    """This file and `test_model_cache_first.py` must class the same modules.

    They ask different questions -- *is it priced* and *does it load cache-first* --
    of one set, and each kept its own copy of that set. `stt/parakeet.py` was in the
    cache-first list and absent from the price list; `stt/moonshine.py` was in neither.
    """
    from tests.test_model_cache_first import _LOADERS

    cache_first = {rel[len("src/"):] for rel in _LOADERS}
    hub = set(hub_fetching_modules())
    # faster-whisper is deliberately outside the cache-first list (it takes
    # `local_files_only=` directly), and it calls none of HUB_LOADERS, so the sets
    # are comparable as they stand.
    assert hub == cache_first, (
        "the model-fetcher classifications have diverged — "
        f"priced-here only: {sorted(hub - cache_first)}; "
        f"cache-first only: {sorted(cache_first - hub)}"
    )


# --- the two sides must be the same set ---------------------------------------


def test_there_are_download_modules_to_check():
    assert len(_download_modules()) >= _MIN_FETCHERS


def test_every_downloader_in_the_tree_is_priced():
    """A new model downloader fails this until someone decides what it costs."""
    missing = sorted(set(_download_modules()) - set(_MODEL_FETCHERS))
    assert not missing, (
        f"these modules fetch model files that no feature is priced for: {missing} -- "
        "add them to depsize._MODEL_FETCHERS with the size and the slugs that pay for it"
    )


def test_nothing_is_priced_that_does_not_exist():
    """Compared against the filesystem, not against `download.py` -- half the priced
    modules are ordinary engine modules that fetch their weights at first use."""
    stale = sorted(rel for rel in _MODEL_FETCHERS if not (SRC / rel).is_file())
    assert not stale, f"priced modules that are gone: {stale}"


# --- the comparison that was missing -------------------------------------------


@pytest.mark.parametrize("rel", sorted(_MODEL_FETCHERS))
def test_the_price_matches_what_the_module_says_about_itself(rel):
    """The docstring and the column are the two facts that disagreed. Hold them equal."""
    priced, _ = _MODEL_FETCHERS[rel]
    stated = _stated_mb(SRC / rel)
    if stated is None:
        # `None` = fetches a model, no figure established anywhere; `0.0` = fetches
        # none. Both are honest answers to a silent docstring. What is not allowed is
        # a number here that the module does not corroborate, since the whole point of
        # this comparison is that two committed figures must agree.
        assert priced in (0.0, None), (
            f"{rel} is priced at {priced} MB but says nothing about its own size -- "
            "state it in the docstring so the two can be checked against each other"
        )
    else:
        assert priced == pytest.approx(stated), (
            f"{rel} says ~{stated} MB in its docstring and is priced at {priced} MB"
        )


def test_the_read_back_voice_is_the_case_that_forced_this():
    """Named explicitly: it is the regression, and 340 MB is not a rounding argument."""
    assert depsize.model_download_mb("read-back") == pytest.approx(340.0)


def test_every_priced_slug_is_a_real_capability():
    """A renamed slug would leave the price attached to nothing, silently."""
    from yazses.system.features import toggleable_slugs

    known = set(toggleable_slugs())
    priced = {slug for _, slugs in _MODEL_FETCHERS.values() for slug in slugs}
    assert priced <= known, f"priced slugs that no longer exist: {sorted(priced - known)}"


def test_a_downloader_may_serve_more_than_one_slug():
    """The sherpa models are one download and three capabilities; pricing is per slug."""
    for slug in ("recimport", "meeting", "diarize"):
        assert depsize.model_download_mb(slug) == pytest.approx(45.0)


# --- what the user is actually shown -------------------------------------------


def test_the_catalogue_column_includes_the_model():
    label = depsize.catalogue_size_label("read-back", has_pip_deps=True)
    assert label == "~352 MB", label


def test_the_column_is_not_just_the_wheels():
    assert depsize.catalogue_size_label("read-back", has_pip_deps=True) != depsize.format_mb(
        depsize.full_download_mb("read-back")
    )


def test_a_feature_with_no_model_is_unchanged():
    """The fix must not inflate the 130-odd capabilities that fetch no model.

    `cocktail` used to be one of the examples here, and that was this file asserting
    the defect: it needs an enrolled voiceprint, so it pulls the ~20 MB ECAPA encoder
    down through `voiceprint/ecapa.py`. A test naming it as fetching nothing is why
    the omission read as intentional.
    """
    assert not depsize.fetches_a_model("chinese-script")
    for slug in ("chinese-script", "overlay", "commands"):
        assert depsize.catalogue_size_label(slug, has_pip_deps=True) == depsize.format_mb(
            depsize.full_download_mb(slug)
        )


def test_a_model_is_priced_even_when_the_feature_has_no_pip_deps():
    """`has_pip_deps=False` used to return early, which would hide a pure-model cost."""
    assert depsize.catalogue_size_label("gaze", has_pip_deps=False) == "~3.7 MB"


def test_the_download_note_names_the_model_and_when_it_arrives():
    note = depsize.download_note("read-back", None)
    assert "~12 MB (7 packages)" in note
    assert "~340 MB of model files on first use" in note


def test_the_note_still_quotes_the_model_when_the_packages_are_installed():
    """The early return said "nothing to download" to a user about to fetch 340 MB."""
    note = depsize.download_note("read-back", [])
    assert "~340 MB" in note
    assert "package" not in note


def test_a_feature_with_neither_says_nothing():
    assert depsize.download_note("nosuchfeature", None) == ""


def test_first_use_is_packages_plus_model():
    assert depsize.first_use_mb("read-back") == pytest.approx(
        depsize.full_download_mb("read-back") + 340.0
    )


def test_first_use_is_none_only_when_there_is_nothing_to_say():
    assert depsize.first_use_mb("nosuchfeature") is None


# --- the guard that could never fire -------------------------------------------


def test_read_back_now_trips_the_loud_threshold():
    assert depsize.is_a_large_download("read-back", None) is True


def test_it_trips_it_on_the_model_alone():
    """Every package already installed, 340 MB still to come: that is still loud."""
    assert depsize.is_a_large_download("read-back", []) is True


def test_a_genuinely_small_feature_is_still_quiet():
    assert depsize.is_a_large_download("chinese-script", None) is False
    assert depsize.is_a_large_download("gaze", None) is False


# --- the sentence the user reads ------------------------------------------------


def test_the_catalogue_legend_says_model_files_are_counted():
    """A column that silently changed meaning is a second wrong number, not a fix."""
    src = (SRC / "yazses" / "cli.py").read_text(encoding="utf-8")
    flowed = " ".join(src.split())
    assert "DOWNLOAD = what a fresh install fetches in total" in flowed
    assert "model files the first time it runs" in flowed
