"""Guards for the AUR package.

The AUR reads `.SRCINFO`, not `PKGBUILD`. They are two files that must say the
same thing, and nothing regenerates one from the other automatically — so a
release that bumps `PKGBUILD` and forgets `.SRCINFO` publishes a package that
advertises the old version and downloads the old tarball, on every Arch user's
machine, silently. That is the failure these tests exist to make loud.

Deliberately parse-only: `makepkg` is not available off Arch, and requiring it
would mean these never run in CI — the same trap the winget/scoop guards fell
into, where a skipped guard was indistinguishable from a passing one.
"""

from __future__ import annotations

import re
from pathlib import Path
from urllib.parse import urlsplit

import pytest

_ARCH = Path(__file__).resolve().parents[1] / "packaging" / "arch"
_PKGBUILD = _ARCH / "PKGBUILD"
_SRCINFO = _ARCH / ".SRCINFO"


def _pkgbuild_field(name: str) -> str:
    m = re.search(rf"^{name}=([^\s#]+)", _PKGBUILD.read_text(), re.MULTILINE)
    assert m, f"{name} not found in PKGBUILD"
    return m.group(1).strip("'\"")


def _srcinfo_field(name: str) -> str:
    m = re.search(rf"^\s*{name} = (.+)$", _SRCINFO.read_text(), re.MULTILINE)
    assert m, f"{name} not found in .SRCINFO"
    return m.group(1).strip()


def test_srcinfo_is_committed():
    """Without it the AUR repo is incomplete and the package will not appear."""
    assert _SRCINFO.is_file(), "packaging/arch/.SRCINFO is missing"


def test_srcinfo_version_matches_pkgbuild():
    assert _srcinfo_field("pkgver") == _pkgbuild_field("pkgver"), (
        "PKGBUILD and .SRCINFO disagree on pkgver — regenerate .SRCINFO "
        "(see packaging/arch/README.md); the AUR reads .SRCINFO"
    )


def test_srcinfo_pkgrel_matches_pkgbuild():
    assert _srcinfo_field("pkgrel") == _pkgbuild_field("pkgrel")


def test_source_url_carries_the_same_version():
    """A version bump that misses the URL downloads the previous release and
    then fails the checksum, which reads as a corrupt mirror to the user."""
    version = _pkgbuild_field("pkgver")
    source = _srcinfo_field("source")
    assert version in source, f"source URL does not mention {version}: {source}"


def test_checksum_is_real():
    """`SKIP` disables integrity checking entirely, and the README used to tell
    the maintainer to paste one in by hand."""
    sha = _srcinfo_field("sha256sums")
    assert sha != "SKIP", "sha256sums=SKIP disables verification of the download"
    assert re.fullmatch(r"[0-9a-f]{64}", sha), f"not a sha256: {sha!r}"


def test_source_is_the_pypi_sdist_not_a_github_tarball():
    """The sdist is what the release actually publishes and what the checksum
    is quoted against; a GitHub tag tarball is regenerated by GitHub and its
    hash is not guaranteed stable over time.

    Compares the parsed host rather than searching the URL for a substring: a
    substring test also passes for ``https://evil.example/files.pythonhosted.org/…``,
    and this assertion is the one that says where users' packages come from.
    """
    parsed = urlsplit(_srcinfo_field("source"))
    assert parsed.scheme == "https", "the source must be fetched over TLS"
    assert parsed.hostname == "files.pythonhosted.org", (
        f"source host is {parsed.hostname!r}, expected the PyPI sdist host"
    )


@pytest.mark.parametrize(
    "dep", ["python-faster-whisper", "python-sounddevice", "portaudio", "pyside6"]
)
def test_runtime_dependencies_are_declared(dep):
    """Each of these is load-bearing: the STT engine, audio capture, the
    PortAudio shared library sounddevice dlopens, and Qt for the tray/overlay."""
    assert f"depends = {dep}" in _SRCINFO.read_text()


def test_package_does_not_pip_install_at_build_time():
    """An earlier revision ran `pip install` inside package(), which downloads
    from PyPI during the build. That is unreproducible and against AUR policy."""
    body = _PKGBUILD.read_text()
    assert "pip install" not in body, (
        "package() must not pip-install; declare real dependencies instead"
    )
