"""The architecture figures must not drift from the code they describe.

`docs/assets/arch/*.svg` are generated by `scripts/gen-arch-figures.py` from the live
feature registry and CLI, and then committed. Generated-and-committed is the pattern
`docs/features.md` uses too — and that one is guarded by
`test_gen_docs.py::test_generated_doc_is_in_sync`, while these were guarded by nothing.

They had drifted, and by a lot. The committed figures said **140 capabilities, 73
wired, 57 commands** when the registry held **144, 80, 58**. A reader of the
architecture page was being shown numbers that were wrong in the specific direction
that flatters the project — 67 unwired capabilities rather than 64 — and nothing in
the suite could tell.

This is the same drift guard, applied to the figures: regenerate, compare, fail.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts/gen-arch-figures.py"
FIGURES = ROOT / "docs/assets/arch"


@pytest.fixture(scope="module")
def gen():
    """Import the hyphenated script by path, as test_gen_docs.py does."""
    spec = importlib.util.spec_from_file_location("gen_arch_figures", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_generator_is_importable(gen):
    """Guard the guard: a rename must fail loudly, not silently skip everything."""
    assert hasattr(gen, "main")


def test_every_committed_figure_matches_the_code(gen):
    """Regenerate each figure and compare it to what is committed.

    `pipeline-heat` and `latency` are derived from the benchmark JSON rather than
    from code, so they are compared too — a benchmark refresh that does not
    regenerate them is the same defect.
    """
    bench = gen.read_benchmarks()
    rows = gen.capability_rows()
    total = sum(w + p for _n, w, p in rows)
    wired = sum(w for _n, w, _p in rows)
    n_cmds, n_leaf = gen.command_counts()

    expected = {
        "system-map.svg": gen.fig_system_map(total, wired, n_cmds, n_leaf),
        "pipeline-heat.svg": gen.fig_pipeline(bench),
        "states.svg": gen.fig_states(),
        "capabilities.svg": gen.fig_capabilities(rows),
        "latency.svg": gen.fig_latency(bench),
        "direction-triage.svg": gen.fig_direction_triage(),
    }

    stale = []
    for name, content in expected.items():
        path = FIGURES / name
        if not path.exists():
            stale.append(f"{name} (missing)")
        elif path.read_text(encoding="utf-8") != content:
            stale.append(name)
    assert not stale, (
        f"these figures no longer match the code: {stale}. Run "
        f"`uv run python scripts/gen-arch-figures.py` and commit the result."
    )


def test_the_figures_agree_with_the_registry_about_how_much_is_unwired(gen):
    """The most load-bearing number on the architecture page, checked directly.

    'N designed but not wired' is the project's own honesty claim about itself. A
    stale figure understates how much has since been wired, which reads as the
    opposite of modesty once someone checks.
    """
    from yazses.system.features import _UNWIRED

    rows = gen.capability_rows()
    planned = sum(p for _n, _w, p in rows)
    assert planned == len(_UNWIRED), (
        f"the figures count {planned} unwired capabilities and the registry has "
        f"{len(_UNWIRED)}"
    )


@pytest.mark.parametrize(
    "name",
    ["system-map.svg", "pipeline-heat.svg", "states.svg", "capabilities.svg",
     "latency.svg", "direction-triage.svg"],
)
def test_every_figure_is_well_formed_and_described(name):
    """A figure with no <desc> is invisible to a screen reader, and these carry
    numbers that appear nowhere else on the page."""
    import xml.etree.ElementTree as ET

    root = ET.parse(FIGURES / name).getroot()
    ns = "{http://www.w3.org/2000/svg}"
    assert root.find(f"{ns}title") is not None, f"{name} has no <title>"
    desc = root.find(f"{ns}desc")
    assert desc is not None and (desc.text or "").strip(), f"{name} has no <desc>"
    assert root.get("role") == "img", f"{name} is not role=img"
