# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: MSKazemi.YazSes
PackageVersion: 2.29.0
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ProductCode: '{F3E8B8A4-1B6C-4F24-9BE8-9B7E58E9C4A2}_is1'
MinimumOSVersion: 10.0.19041.0
ReleaseDate: 2026-08-19
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/MSKazemi/yazses/releases/download/v2.29.0/YazSes-2.29.0-windows-x64.exe
    InstallerSha256: 2B4FD82E53BB8711404C2B1E79642021E09CCCA3E39D12546372CBC61F182C6D
ManifestType: installer
ManifestVersion: 1.6.0
