// Privacy gates — ADR-MOB-007 turned into build failures.
//
// The promise is that your voice never leaves the device. On Android that
// promise is decided by the MERGED manifest and by TRANSITIVE dependencies, so
// an SDK three levels down can add INTERNET and phone-home behaviour that no
// reviewer spots in a diff. A keyboard is the most sensitive app class on the
// platform — the system itself warns users about installing one — so the
// property has to be enforced by the build rather than by care.
//
// Every gate here fails with the fix, not just the fact. A gate that says "you
// broke a rule" and stops is a gate contributors learn to resent.

val adr = "docs/mobile/adr/adr-mob-007-privacy-permissions-lifecycle.md"

// ---------------------------------------------------------------------------
// 1. Manifest golden-diff.
//
// Every permission and every exported component the app declares, in one
// reviewable file. A permission that appears without this file changing is a
// permission nobody agreed to.
// ---------------------------------------------------------------------------

val goldenManifest = rootProject.layout.projectDirectory.file("privacy/manifest-golden.txt")

/** Permissions and exported components, read straight out of the manifests. */
fun collectManifestFacts(): List<String> {
    val facts = sortedSetOf<String>()
    val permission = Regex("""<uses-permission[^>]*android:name="([^"]+)"""")
    val exported = Regex("""android:exported="true"""")
    val cleartext = Regex("""android:usesCleartextTraffic="([^"]+)"""")

    rootProject.subprojects.forEach { sub ->
        val manifest = sub.file("src/main/AndroidManifest.xml")
        if (!manifest.isFile) return@forEach
        val text = manifest.readText()
        permission.findAll(text).forEach { facts += "permission ${it.groupValues[1]} (${sub.path})" }
        if (exported.containsMatchIn(text)) facts += "exported-component (${sub.path})"
        cleartext.find(text)?.let { facts += "usesCleartextTraffic=${it.groupValues[1]} (${sub.path})" }
    }
    return facts.toList()
}

val checkManifestGolden by tasks.registering {
    group = "verification"
    description = "Fails when the declared permissions or exported components change."

    val actual = collectManifestFacts()
    val goldenFile = goldenManifest.asFile

    doLast {
        val expected = if (goldenFile.isFile) {
            goldenFile.readLines().map { it.trim() }.filter { it.isNotEmpty() && !it.startsWith("#") }
        } else {
            emptyList()
        }
        if (actual != expected) {
            val added = actual - expected.toSet()
            val removed = expected - actual.toSet()
            throw GradleException(
                buildString {
                    appendLine("The app's privacy surface changed.")
                    appendLine()
                    if (added.isNotEmpty()) {
                        appendLine("  ADDED:")
                        added.forEach { appendLine("    + $it") }
                    }
                    if (removed.isNotEmpty()) {
                        appendLine("  REMOVED:")
                        removed.forEach { appendLine("    - $it") }
                    }
                    appendLine()
                    appendLine("This is not automatically wrong — it is something a human has to agree to.")
                    appendLine("If the change is intended, in the SAME pull request:")
                    appendLine()
                    appendLine("  1. update ${goldenFile.relativeTo(rootProject.projectDir)}")
                    appendLine("  2. update the permission table in $adr")
                    appendLine()
                    appendLine("Regenerate the golden file with:  ./gradlew updateManifestGolden")
                }
            )
        }
    }
}

val updateManifestGolden by tasks.registering {
    group = "verification"
    description = "Rewrites the golden manifest file from the current manifests."

    val actual = collectManifestFacts()
    val goldenFile = goldenManifest.asFile

    doLast {
        goldenFile.parentFile.mkdirs()
        goldenFile.writeText(
            buildString {
                appendLine("# Every permission and exported component the Android app declares.")
                appendLine("# Generated by `./gradlew updateManifestGolden`, reviewed by a human.")
                appendLine("# Changing this file without updating the permission table in")
                appendLine("# $adr is the thing the gate exists to prevent.")
                actual.forEach { appendLine(it) }
            }
        )
        logger.lifecycle("Wrote ${goldenFile.relativeTo(rootProject.projectDir)}")
    }
}

// ---------------------------------------------------------------------------
// 2 + 3. Dependency allow-list, and network containment.
//
// INTERNET belongs to :model and nowhere else. The dictation path — audio, vad,
// stt, postprocess, ime — must have no reachable network code, as a property the
// build checks rather than a sentence in a README.
// ---------------------------------------------------------------------------

/** Artefact groups that mean "this module can talk to the network". */
val networkArtefacts = listOf(
    "com.squareup.okhttp3", "com.squareup.retrofit2", "io.ktor",
    "org.apache.httpcomponents", "com.google.firebase", "com.android.volley",
)

/** Never acceptable anywhere, at any depth. */
val bannedArtefacts = listOf(
    "com.google.firebase:firebase-analytics",
    "com.google.firebase:firebase-crashlytics",
    "com.crashlytics", "io.sentry", "com.amplitude", "com.mixpanel",
    "com.appsflyer", "com.facebook.android:facebook-core",
)

/** Modules permitted to reach the network. Exactly one. */
val networkAllowedModules = setOf(":model")

/** Every external module reachable on a classpath, at any depth. */
fun componentsOf(root: ResolvedComponentResult): Set<String> {
    val found = sortedSetOf<String>()
    val seen = mutableSetOf<ComponentIdentifier>()
    fun walk(component: ResolvedComponentResult) {
        if (!seen.add(component.id)) return
        (component.id as? ModuleComponentIdentifier)?.let { found += "${it.group}:${it.module}" }
        component.dependencies.filterIsInstance<ResolvedDependencyResult>()
            .forEach { walk(it.selected) }
    }
    walk(root)
    return found
}

val checkDependencyPolicy by tasks.registering {
    group = "verification"
    description = "No analytics SDKs anywhere; no network code outside :model."

    // The RESOLVED graph, not the declared list.
    //
    // This read `conf.dependencies` -- what each module writes in its own build
    // file -- while the threat this gate exists for, stated at the top of this
    // file, is "an SDK three levels down". A directly declared analytics library
    // failed the build; the same library arriving transitively did not.
    // Reproduced: `org.opentest4j` sits on :core:contract-test's classpath via
    // junit-jupiter, and banning it changed nothing.
    //
    // `rootComponent` is a Provider, so the graph resolves when the task runs
    // rather than while the build is being configured. Runtime classpaths only:
    // they are what ships and what can phone home.
    val graphs: List<Pair<String, Provider<ResolvedComponentResult>>> =
        rootProject.subprojects.flatMap { sub ->
            sub.configurations
                .filter { it.isCanBeResolved && it.name.endsWith("RuntimeClasspath") }
                .map { sub.path to it.incoming.resolutionResult.rootComponent }
        }

    doLast {
        val problems = mutableListOf<String>()
        val resolved: Map<String, Set<String>> = graphs
            .groupBy({ it.first }, { componentsOf(it.second.get()) })
            .mapValues { (_, sets) -> sets.flatten().toSet() }

        // A gate that resolved nothing reports nothing, and reads exactly like a
        // clean build. Say so instead.
        check(resolved.values.sumOf { it.size } > 0) {
            "checkDependencyPolicy resolved no dependencies at all, so it cannot have " +
                "checked anything. Either no module has a runtime classpath any more, " +
                "or resolution is failing silently — fix that before trusting a pass."
        }

        resolved.forEach { (path, artefacts) ->
            artefacts.forEach { artefact ->
                if (bannedArtefacts.any { artefact.startsWith(it) }) {
                    problems += "$path depends on $artefact — analytics and crash reporting are never allowed"
                }
                if (path !in networkAllowedModules &&
                    networkArtefacts.any { artefact.startsWith(it) }
                ) {
                    problems += "$path depends on $artefact — only :model may reach the network"
                }
            }
        }

        if (problems.isNotEmpty()) {
            throw GradleException(
                buildString {
                    appendLine("Dependency policy violated:")
                    problems.forEach { appendLine("  $it") }
                    appendLine()
                    appendLine("The dictation path (:core:audio -> :core:vad -> :core:stt ->")
                    appendLine(":core:postprocess -> :feature:ime) must have no reachable network")
                    appendLine("code. INTERNET is declared in :model alone, and model downloads are")
                    appendLine("the only thing that uses it — see $adr.")
                    appendLine()
                    appendLine("If a module genuinely needs data from the network, it should ask")
                    appendLine(":model for it through an interface rather than fetch it itself.")
                }
            )
        }
    }
}

// ---------------------------------------------------------------------------
// 4. No content in logs.
//
// Diagnostics are metadata — durations, sizes, states. A log line carrying the
// transcript is the same leak as sending it somewhere, because logcat is readable
// by the user, by a bug report, and by anything with READ_LOGS.
// ---------------------------------------------------------------------------

/** Identifiers that name recognised speech or raw audio. */
val contentIdentifiers = listOf(
    "transcript", "utterance", "recognisedText", "recognizedText",
    "spokenText", "rawText", "finalText", "pcm", "samples", "audioBuffer",
)

/**
 * The argument list of every log call in [text], with the line the call starts on.
 *
 * Scanned as a statement rather than a line, because a leak does not care about
 * formatting and this codebase already wraps 26 calls. These are the same leak:
 *
 *     Log.d("tag", "got $transcript")          // caught
 *     Log.d(                                   // was not caught
 *         "tag",
 *         "got $transcript",
 *     )
 *
 * A wrapped call is not an unusual shape -- it is what a log line with a tag and an
 * interpolated message becomes the moment it passes a line-length rule, so the
 * formatting most likely to appear is the formatting the gate could not see.
 *
 * Parentheses inside string literals do not nest (`"a )"` closes nothing) and raw
 * strings are opaque, so the scan tracks both. Without that, one `")"` in a message
 * would end the argument list early and every later call in the file would be read
 * at the wrong offset.
 */
fun logCallArguments(text: String): List<Pair<Int, String>> {
    val logCall = Regex("""\b(?:Log\.[vdiwe]|logger\.\w+|println)\s*\(""")
    val out = mutableListOf<Pair<Int, String>>()
    for (match in logCall.findAll(text)) {
        val open = match.range.last
        var index = open + 1
        var depth = 1
        var inRawString = false
        var inString = false
        while (index < text.length && depth > 0) {
            val char = text[index]
            when {
                inRawString -> if (text.startsWith("\"\"\"", index)) {
                    inRawString = false
                    index += 2
                }
                inString -> when (char) {
                    '\\' -> index++
                    '"' -> inString = false
                }
                text.startsWith("\"\"\"", index) -> {
                    inRawString = true
                    index += 2
                }
                char == '"' -> inString = true
                char == '(' -> depth++
                char == ')' -> depth--
            }
            index++
        }
        val line = text.substring(0, match.range.first).count { it == '\n' } + 1
        out += line to text.substring(open + 1, (index - 1).coerceIn(open + 1, text.length))
    }
    return out
}

val checkNoContentLogging by tasks.registering {
    group = "verification"
    description = "Forbids transcript text or raw audio in a log statement."

    val sources = rootProject.subprojects.flatMap { sub ->
        sub.fileTree("src").matching { include("**/*.kt") }.files.map { sub.path to it }
    }
    val logCall = Regex("""\b(?:Log\.[vdiwe]|logger\.\w+|println)\s*\(""")

    doLast {
        val problems = mutableListOf<String>()
        sources.forEach { (path, file) ->
            logCallArguments(file.readText()).forEach { (line, arguments) ->
                contentIdentifiers.forEach { identifier ->
                    if (Regex("""\b$identifier\b""", RegexOption.IGNORE_CASE).containsMatchIn(arguments)) {
                        problems += "${file.relativeTo(rootProject.projectDir)}:$line ($path) logs `$identifier`"
                    }
                }
            }
        }
        if (problems.isNotEmpty()) {
            throw GradleException(
                buildString {
                    appendLine("Content in a log statement:")
                    problems.forEach { appendLine("  $it") }
                    appendLine()
                    appendLine("logcat is readable by the user, by any bug report, and by anything")
                    appendLine("holding READ_LOGS. A transcript in a log line is the same leak as")
                    appendLine("sending it somewhere — see $adr.")
                    appendLine()
                    appendLine("Log metadata instead: how long it took, how many characters, which")
                    appendLine("state the session moved to. Never the words.")
                }
            )
        }
    }
}

// One task to run them all, and `check` depends on it so none can be skipped.
val checkPrivacy by tasks.registering {
    group = "verification"
    description = "Every ADR-MOB-007 privacy gate."
    dependsOn(checkManifestGolden, checkDependencyPolicy, checkNoContentLogging)
}
