#!/usr/bin/env python3
"""Generate the architecture figures for docs/architecture.md.

    docs/assets/arch/system-map.svg     the subsystem map, status-coded
    docs/assets/arch/pipeline-heat.svg  the dictation pipeline, coloured by measured cost
    docs/assets/arch/capabilities.svg   140 capabilities: wired vs designed-not-built
    docs/assets/arch/latency.svg        measured decode latency per model

Run:  uv run python scripts/gen-arch-figures.py

Every number in these figures comes from something that can be checked:

  * capability counts come from the live registry (`yazses.system.features`) —
    the same one `yazses features` prints, so a figure claiming a capability is
    wired is making the claim the CLI makes;
  * every timing comes from `docs/benchmarks.md`, parsed at generation time, so
    a figure cannot disagree with the benchmark table a reader can scroll to.
    `paper/` (where the raw JSON lives) is gitignored, so the published page is
    the tracked source of truth;
  * command counts come from the generated `docs/command-index.md`;
  * the "designed, not built" blocks each carry an evidence pointer to the file
    that records the decision, rendered into the page's own table.

Regenerate after changing the feature registry or re-running the benchmarks.
The figures are plain SVG with no script and no external reference: they survive
the `material/privacy` plugin, inline cleanly into the page (so they inherit the
light/dark palette), and animate from `docs/assets/extra.css`.

Two things here are checks rather than judgement calls:

  * `fit()` refuses to emit a label wider than the shape holding it, so a
    clipped or overflowing label fails generation instead of shipping;
  * the colours were validated for lightness band, chroma, colour-vision
    separation and contrast against both Material surfaces this site renders on
    (light #ffffff, slate #1e2129) — see `docs/assets/extra.css`.

The canvas width matches the rendered content column (757 px measured), so the
type renders at roughly its authored size instead of being scaled down into
illegibility.
"""
from __future__ import annotations

import re
from pathlib import Path

from yazses.config import Config
from yazses.system.features import grouped_features

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "assets" / "arch"

BANNER = "<!-- GENERATED by scripts/gen-arch-figures.py — do not edit by hand. -->"

#: Canvas width every figure shares. The docs content column measures 757 px on
#: a wide viewport, so authoring at 760 keeps text at ~1:1 rather than scaled.
W = 760

# Type sizes, in the same units. Kept here so the fit checks and the CSS agree.
SZ_L, SZ_S, SZ_M, SZ_V, SZ_BAND = 13.0, 11.0, 10.5, 12.0, 10.0


# --------------------------------------------------------------------------- #
# Inputs
# --------------------------------------------------------------------------- #
def read_benchmarks() -> dict:
    """Parse the measured numbers out of docs/benchmarks.md.

    Deliberately strict: if the tables move or are reworded this raises rather
    than silently emitting a figure that disagrees with the published page.
    """
    text = (DOCS / "benchmarks.md").read_text(encoding="utf-8")

    models: dict[str, dict[str, float]] = {}
    # | `base.en` **(default)** | 0.85 s | **1.56 s** | 3.53 s | 0.283 (…) |
    row = re.compile(
        r"^\|\s*`([a-z.]+)`[^|]*\|\s*\*{0,2}([\d.]+)\s*s\*{0,2}\s*\|"
        r"\s*\*{0,2}([\d.]+)\s*s\*{0,2}\s*\|\s*\*{0,2}([\d.]+)\s*s\*{0,2}\s*\|",
        re.M,
    )
    for name, cold, median, p95 in row.findall(text):
        models[name] = {
            "cold_s": float(cold),
            "median_ms": float(median) * 1000.0,
            "p95_ms": float(p95) * 1000.0,
        }
    for required in ("tiny.en", "base.en", "small.en"):
        if required not in models:
            raise SystemExit(
                f"docs/benchmarks.md: could not parse the speed row for {required!r} "
                "— has the table changed? Fix the parser in scripts/gen-arch-figures.py."
            )

    stages = {
        label: _stage_ms(text, label)
        for label in (
            "VAD gate",
            "Text cleaner",
            "Disfluency filter",
            "Command grammar (dictation)",
        )
    }
    overhead = _stage_ms(text, "**Total non-decode overhead**")

    if "i7-1370P" not in text:
        raise SystemExit(
            "docs/benchmarks.md no longer names the i7-1370P test machine; update "
            "the provenance string in scripts/gen-arch-figures.py."
        )
    machine = "measured: i7-1370P · int8 on CPU, no GPU"
    return {"models": models, "stages": stages, "overhead_ms": overhead, "machine": machine}


def _stage_ms(text: str, label: str) -> float:
    m = re.search(rf"^\|\s*{re.escape(label)}\s*\|\s*\*{{0,2}}([\d.]+)\s*ms", text, re.M)
    if not m:
        raise SystemExit(
            f"docs/benchmarks.md: could not find a timing row for {label!r} "
            "— fix the parser in scripts/gen-arch-figures.py."
        )
    return float(m.group(1))


def capability_rows() -> list[tuple[str, int, int]]:
    """(category, wired, designed-but-not-wired) straight from the live registry."""
    return [
        (name, sum(1 for f in feats if f.wired), sum(1 for f in feats if not f.wired))
        for name, _blurb, feats in grouped_features(Config())
    ]


def command_counts() -> tuple[int, int]:
    index = (DOCS / "command-index.md").read_text(encoding="utf-8")
    tops = re.findall(r"^## `yazses ([\w-]+)", index, re.M)
    subs = re.findall(r"^### `yazses ([\w-]+) ", index, re.M)
    if not tops:
        raise SystemExit("docs/command-index.md looks empty — run scripts/gen-docs.py first.")
    return len(tops), len(tops) - len(set(subs)) + len(subs)


# --------------------------------------------------------------------------- #
# SVG helpers
# --------------------------------------------------------------------------- #
#: Rough advance widths for the site's UI sans (Inter), as a fraction of the font
#: size. Only used to catch labels that would overflow their shape — it needs to
#: be slightly pessimistic, not typographically exact.
_NARROW = set("iltjfIr!.,:;'`|·()[]-")
_WIDE = set("MWmw@%—")


def est_width(s: str, size: float) -> float:
    total = 0.0
    for ch in s:
        if ch in _NARROW:
            total += 0.34
        elif ch in _WIDE:
            total += 0.92
        elif ch.isupper() or ch.isdigit():
            total += 0.64
        else:
            total += 0.55
    return total * size


def fit(s: str, size: float, avail: float, where: str) -> str:
    """Refuse to emit a label that would overflow the shape holding it."""
    w = est_width(s, size)
    if w > avail:
        raise SystemExit(
            f"{where}: label {s!r} needs ~{w:.0f}px at {size:g}px but only {avail:.0f}px "
            "is available. Shorten the label or widen the shape."
        )
    return s


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def svg(name: str, height: float, title: str, desc: str, body: list[str]) -> str:
    """Wrap a body in a self-contained, accessible root <svg>.

    role="img" plus <title>/<desc> is what a screen reader announces; the page
    also carries a data table under every figure, so no value is reachable only
    from the graphic.
    """
    head = (
        f'<svg class="yz-fig yz-fig--{name}" viewBox="0 0 {W} {height:g}" '
        f'xmlns="http://www.w3.org/2000/svg" role="img" '
        f'aria-labelledby="{name}-t {name}-d">'
    )
    lines = [
        BANNER,
        head,
        f'<title id="{name}-t">{esc(title)}</title>',
        f'<desc id="{name}-d">{esc(desc)}</desc>',
        *body,
        "</svg>",
    ]
    # No blank lines: Python-Markdown must see one uninterrupted raw HTML block.
    return "\n".join(ln for ln in lines if ln.strip()) + "\n"


def text(x: float, y: float, s: str, cls: str = "yz-l", anchor: str = "start") -> str:
    a = f' text-anchor="{anchor}"' if anchor != "start" else ""
    return f'<text class="{cls}" x="{x:g}" y="{y:g}"{a}>{esc(s)}</text>'


def box(x: float, y: float, w: float, h: float, cls: str = "yz-box", rx: float = 7) -> str:
    return f'<rect class="{cls}" x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="{rx:g}"/>'


def tip(s: str) -> str:
    """A native SVG tooltip — the hover layer, with no script."""
    return f"<title>{esc(s)}</title>"


def hline(x1: float, x2: float, y: float) -> str:
    return f'<path class="yz-flow" d="M {x1:g} {y:g} L {x2:g} {y:g}" marker-end="url(#yz-arrow)"/>'


def vline(x: float, y1: float, y2: float) -> str:
    return f'<path class="yz-flow" d="M {x:g} {y1:g} L {x:g} {y2:g}" marker-end="url(#yz-arrow)"/>'


def vpacket(x: float, y1: float, y2: float, delay: float = 0.0) -> str:
    return (
        f'<circle class="yz-pkt yz-pkt--v" cx="{x:g}" cy="{y1:g}" r="3" '
        f'style="--yz-dist:{y2 - y1 - 7:g}px;--yz-delay:{delay:g}s"/>'
    )


def hpacket(x: float, y: float, dist: float, cls: str, delay: float = 0.0) -> str:
    return (
        f'<circle class="yz-pkt {cls}" cx="{x:g}" cy="{y:g}" r="4.5" '
        f'style="--yz-dist:{dist:g}px;--yz-delay:{delay:g}s"/>'
    )


def defs() -> str:
    return (
        '<defs><marker id="yz-arrow" viewBox="0 0 10 10" refX="8.5" refY="5" '
        'markerWidth="5" markerHeight="5" orient="auto-start-reverse">'
        '<path class="yz-arrowhead" d="M 0 1.5 L 8.5 5 L 0 8.5 z"/></marker></defs>'
    )


def band(y_mid: float, label: str, gutter: float) -> str:
    fit(label, SZ_BAND, gutter, "band label")
    return text(gutter, y_mid + 3.5, label, "yz-band", "end")


def cell(x: float, y: float, w: float, h: float, head: str, sub: str, hover: str,
         cls: str = "yz-box", where: str = "cell") -> list[str]:
    """A labelled block: one bold line, one quiet line, both fit-checked."""
    pad = 14
    fit(head, SZ_L, w - pad, where)
    fit(sub, SZ_S, w - pad, where)
    return [
        f'<g class="yz-node">{tip(hover)}',
        box(x, y, w, h, cls),
        text(x + w / 2, y + h / 2 - 2, head, "yz-l", "middle"),
        text(x + w / 2, y + h / 2 + 14, sub, "yz-s", "middle"),
        "</g>",
    ]


def spread(x: float, total_w: float, n: int, gap: float) -> tuple[float, list[float]]:
    """Column width and left edges for n equal blocks across total_w."""
    w = (total_w - gap * (n - 1)) / n
    return w, [x + i * (w + gap) for i in range(n)]


# --------------------------------------------------------------------------- #
# Figure 1 — the subsystem map, status-coded
# --------------------------------------------------------------------------- #
#: Designed and documented, deliberately not built. Each carries the record that
#: says so, so "planned" is never a bare assertion — the page renders these
#: pointers in a table beneath the figure.
PLANNED_BLOCKS = [
    ("Android keyboard", "in design", "docs/mobile/"),
    ("Cloud escalation", "deliberately unbuilt", "roadmap: designed, deferred"),
    ("Speech adapters", "LoRA, gated on a win", "[personalize] lora"),
    ("Code-switch", "routing ships, not models", "src/yazses/polyglot/"),
]


def fig_system_map(total: int, wired: int, n_cmds: int, n_leaf: int) -> str:
    planned = total - wired
    gutter, px = 92, 102
    pw = W - px - 12
    b: list[str] = [defs()]

    # ---- control plane -----------------------------------------------------
    b.append(band(42, "CONTROL", gutter))
    w, xs = spread(px, pw, 3, 12)
    for x, (head, sub, hover) in zip(
        xs,
        [
            ("yazses CLI", f"{n_cmds} commands", f"{n_cmds} top-level commands, {n_leaf} counting subcommands"),
            ("yazses settings", "Qt window", "A settings window generated from the same feature registry the CLI reads"),
            ("yazses-tray", "5-colour badge", "Top-bar state badge; supervised and relaunched if it dies"),
        ],
    ):
        b += cell(x, 16, w, 52, head, sub, hover, where="control")
    b.append(vline(W / 2, 68, 96))
    b.append(vpacket(W / 2, 68, 96))
    b.append(text(W / 2 + 12, 87, "JSON-RPC 2.0 · Unix socket · named pipe on Windows", "yz-s yz-halo"))

    # ---- transport ---------------------------------------------------------
    b.append(band(115, "TRANSPORT", gutter))
    b.append(f'<g class="yz-node">{tip("src/yazses/ipc/ — newline-delimited JSON-RPC 2.0")}')
    b.append(box(px, 96, pw, 38))
    b.append(text(px + pw / 2, 120, "IPC server · ipc/", "yz-l", "middle"))
    b.append("</g>")
    b.append(vline(W / 2, 134, 162))
    b.append(vpacket(W / 2, 134, 162, 0.5))

    # ---- the daemon --------------------------------------------------------
    b.append(band(250, "DAEMON", gutter))
    b.append(box(px, 162, pw, 186, "yz-box yz-box--shell"))
    b.append(text(px + 14, 184, "yazses-daemon — orchestrator (core/daemon.py) · 10 states", "yz-l"))
    b.append(text(px + 14, 200, "one long-lived process; every stage below runs inside it", "yz-s"))

    stages = [
        ("1 · Hotkey", "keyboard or EMG", "hotkeys/, platform/emg/ — a squeeze on a USB serial device is a hotkey"),
        ("2 · Audio", "capture · VAD · pad", "audio/ — record, drop near-silence, prepend a lead-in"),
        ("3 · Speech", "Whisper or Parakeet", "stt/ — pluggable behind the SttEngine protocol"),
        ("4 · Post", "clean · punctuate", "postprocess/ — artefact strip, disfluency, continuation spacing"),
        ("5 · Commands", "regex, then a router", "commands/ — Tier-1 grammar, optional Tier-2 SLM router"),
        ("6 · Dispatch", "text or key sequence", "commands/dispatch.py — the fork in the pipeline"),
    ]
    cx, cw = px + 14, (pw - 28 - 2 * 10) / 3
    rows_y = (212, 284)
    for r, ry in enumerate(rows_y):
        for c in range(3):
            head, sub, hover = stages[r * 3 + c]
            x = cx + c * (cw + 10)
            b += cell(x, ry, cw, 48, head, sub, hover, "yz-box yz-box--chip", "stage")
            if c:
                b.append(hline(x - 10, x - 2, ry + 24))
        b.append(hpacket(cx + cw / 2, ry + 24, 2 * (cw + 10), f"yz-pkt--h{r + 1}"))
    # The elbow carrying the burst from the end of row one to the start of row two.
    ex = cx + 3 * cw + 2 * 10
    b.append(
        f'<path class="yz-flow" d="M {ex - cw / 2:g} 260 L {ex - cw / 2:g} 272 '
        f'L {cx + cw / 2:g} 272 L {cx + cw / 2:g} 282" marker-end="url(#yz-arrow)"/>'
    )
    b.append(text(px + 14, 340, "hold → speak → release · the moving dot is one burst crossing the pipeline", "yz-s"))
    b.append(vline(W / 2, 348, 376))
    b.append(vpacket(W / 2, 348, 376, 1.0))

    # ---- delivery ----------------------------------------------------------
    b.append(band(402, "DELIVERY", gutter))
    w, xs = spread(px, pw, 3, 12)
    for x, (head, sub, hover) in zip(
        xs,
        [
            ("Injector", "ydotool · xdotool · wtype", "inject/ — ydotool is the default where available; it is the one path that works on Wayland"),
            ("Key sequence", "ctrl+z · ctrl+s · …", "Commands become real key events rather than typed text"),
            ("yazses-agent", "over SSH, text only", "remote/ — the text travels to another host; the audio never leaves this one"),
        ],
    ):
        b += cell(x, 376, w, 52, head, sub, hover, where="delivery")
    b.append(text(W / 2, 446, "↓ into the focused application", "yz-s", "middle"))

    # ---- cross-cutting -----------------------------------------------------
    b.append(band(490, "SUPPORT", gutter))
    w, xs = spread(px, pw, 4, 10)
    for x, (head, sub, hover) in zip(
        xs,
        [
            ("Platform", "linux · macos · windows", "platform/base.py — Protocol interfaces each OS implements; adding one touches no other code"),
            ("Config", "self-repairing", "config.py + configcheck.py — no config file can stop the daemon starting"),
            ("Registry", f"{total} capabilities", f"system/features.py — {wired} wired, {planned} designed but not wired"),
            ("Corpus", "opt-in · encrypted", "learning/ — machine-bound encryption, off by default, never uploaded"),
        ],
    ):
        b += cell(x, 464, w, 52, head, sub, hover, where="support")

    # ---- designed, not built ----------------------------------------------
    b.append(band(548, "DESIGNED,", gutter))
    b.append(band(562, "NOT BUILT", gutter))
    w, xs = spread(px, pw, 4, 10)
    for x, (head, sub, ev) in zip(xs, PLANNED_BLOCKS):
        b += cell(x, 530, w, 52, head, sub, f"{head} — {sub} ({ev})", "yz-box yz-box--plan", "planned")
    b.append(
        text(px, 604, "Documented, decided, and deliberately absent from the running system — see the table below.", "yz-s")
    )

    return svg(
        "system-map",
        620,
        "YazSes subsystem map",
        "Six bands. A control plane of CLI, settings window and tray talks over JSON-RPC to an "
        "IPC server, which drives the yazses-daemon orchestrator. Inside the daemon six pipeline "
        "stages run in order: hotkey, audio, speech, post-processing, command classification, "
        "dispatch. Dispatch delivers typed text, a key sequence, or text forwarded over SSH to "
        "another host. A support band holds the platform protocols, the self-repairing config, "
        f"the {total}-capability registry, and the opt-in encrypted learning corpus. A final band "
        "shows four subsystems that are designed and deliberately not built: the Android "
        "keyboard, cloud escalation, personal speech adapters, and code-switch models.",
        b,
    )


# --------------------------------------------------------------------------- #
# Figure 2 — the pipeline, coloured by measured cost
# --------------------------------------------------------------------------- #
def fig_pipeline(bench: dict) -> str:
    st = bench["stages"]
    decode = bench["models"]["base.en"]["median_ms"]
    overhead = bench["overhead_ms"]
    total = decode + overhead
    b: list[str] = [defs()]

    # Nine stages; five are separately timed. The other four say so rather than
    # being given a number nobody measured.
    stages = [
        ("Hotkey", "hold starts it", None),
        ("Capture", "mic → buffer", None),
        ("VAD gate", "drop silence", st["VAD gate"]),
        ("Padding", "lead-in", None),
        ("Decode", "faster-whisper", decode),
        ("Cleaner", "strip artefacts", st["Text cleaner"]),
        ("Disfluency", "fillers, repeats", st["Disfluency filter"]),
        ("Grammar", "text or command", st["Command grammar (dictation)"]),
        ("Inject", "into the app", None),
    ]

    def draw(items, x0, y, cw, gap, tag):
        for i, (name, sub, ms) in enumerate(items):
            x = x0 + i * (cw + gap)
            if ms is None:
                grp, cls = "yz-node yz-untimed", "yz-box yz-box--untimed"
                label, hover = "not timed", f"{name} — not separately timed"
            else:
                # Sequential ramp by order of magnitude. The decode is the only
                # hot cell, which is the finding rather than a styling choice.
                step = 7 if ms > 100 else 2
                grp, cls = f"yz-node yz-heat--{step}", "yz-box yz-heat-fill"
                label = f"{ms / 1000:.2f} s" if ms >= 100 else f"{ms:.3f} ms"
                hover = f"{name} — median {label}, {ms / total * 100:.2f}% of the burst"
            fit(name, SZ_L, cw - 12, tag)
            fit(sub, SZ_S, cw - 12, tag)
            b.append(f'<g class="{grp}">{tip(hover)}')
            b.append(box(x, y, cw, 74, cls))
            b.append(text(x + cw / 2, y + 26, name, "yz-l yz-on-heat", "middle"))
            b.append(text(x + cw / 2, y + 43, sub, "yz-s yz-on-heat", "middle"))
            b.append(text(x + cw / 2, y + 63, label, "yz-v yz-on-heat", "middle"))
            b.append("</g>")
            if i:
                b.append(hline(x - gap, x - 2, y + 37))

    x0, avail = 18, W - 36
    cw1 = (avail - 4 * 8) / 5
    cw2 = (avail - 3 * 8) / 4
    draw(stages[:5], x0, 30, cw1, 8, "pipeline row 1")
    draw(stages[5:], x0, 132, cw2, 8, "pipeline row 2")
    b.append(hpacket(x0 + cw1 / 2, 67, 4 * (cw1 + 8), "yz-pkt--h1"))
    b.append(hpacket(x0 + cw2 / 2, 169, 3 * (cw2 + 8), "yz-pkt--h2"))
    b.append(
        f'<path class="yz-flow" d="M {W - 18 - cw1 / 2:g} 104 L {W - 18 - cw1 / 2:g} 118 '
        f'L {x0 + cw2 / 2:g} 118 L {x0 + cw2 / 2:g} 130" marker-end="url(#yz-arrow)"/>'
    )

    # ---- the same burst, drawn to scale -----------------------------------
    rx, rw = 18, W - 36
    b.append(text(rx, 240, f"The same burst drawn to scale — {total / 1000:.2f} s end to end", "yz-l"))
    b.append(f'<g class="yz-node yz-heat--7">{tip(f"faster-whisper base.en decode: {decode:.0f} ms of {total:.0f} ms")}')
    b.append(box(rx, 250, rw, 28, "yz-bar yz-heat-fill", 4))
    b.append(text(rx + 12, 269, f"Decode — {decode / 1000:.2f} s · {decode / total * 100:.2f}%", "yz-v yz-on-heat"))
    b.append("</g>")

    # The non-decode sliver is a fifth of a pixel at this scale, so it is
    # magnified rather than drawn, and the magnification is stated on the figure.
    sliver = overhead / total * rw
    factor = 5000
    b.append(f'<path class="yz-lead" d="M {rx + rw - 1:g} 278 L {rx + rw - 1:g} 296 L {W - 250:g} 296"/>')
    b.append(text(W - 246, 292, f"everything else: {overhead:.2f} ms — {sliver:.2f} px wide here", "yz-s yz-halo"))

    mw = W - 300
    scale = mw / overhead
    order = [
        ("Disfluency filter", st["Disfluency filter"]),
        ("Command grammar", st["Command grammar (dictation)"]),
        ("VAD gate", st["VAD gate"]),
        ("Text cleaner", st["Text cleaner"]),
    ]
    b.append(text(rx, 328, f"That 0.29 ms, magnified ×{factor:,}", "yz-l"))
    cx = rx
    for i, (name, ms) in enumerate(order):
        seg = ms * scale
        b.append(f'<g class="yz-node yz-heat--{4 - i}">{tip(f"{name} — median {ms:.4f} ms")}')
        # A 2 px surface gap between segments, never a stroke around them.
        b.append(box(cx, 336, max(seg - 2, 1), 24, "yz-bar yz-heat-fill", 3))
        b.append("</g>")
        cx += seg
    b.append(
        text(rx, 378, " · ".join(f"{n} {ms:.3f}" for n, ms in order) + " ms", "yz-s")
    )
    b.append(
        text(
            rx,
            400,
            f"All non-decode work is {overhead / total * 100:.2f}% of a burst. Optimising anything "
            "but the speech model would not be measurable.",
            "yz-s",
        )
    )
    b.append(text(W - 18, 418, bench["machine"], "yz-m", "end"))

    return svg(
        "pipeline-heat",
        430,
        "The dictation pipeline, coloured by measured cost",
        "Nine stages in order: hotkey, capture, VAD gate, padding, decode, cleaner, disfluency "
        "filter, command grammar, injection. Five are separately timed; the other four are marked "
        f"as not timed. The decode takes {decode:.0f} milliseconds and every other measured stage "
        f"together takes {overhead:.2f} milliseconds — {overhead / total * 100:.2f}% of the burst. "
        "A scale ribbon shows the decode filling essentially the whole burst, with the remainder "
        f"magnified {factor} times to be visible at all.",
        b,
    )


# --------------------------------------------------------------------------- #
# Figure 3 — the daemon state machine
# --------------------------------------------------------------------------- #
#: Every transition here was read off `core/daemon.py`. Mermaid's automatic
#: layout turns this hub-and-spoke shape into overlapping labels, so it is laid
#: out by hand — and laying it out by hand is also what makes room to be honest
#: about the two states the daemon never actually enters.
def fig_states() -> str:
    b: list[str] = [defs()]
    spine = [
        ("LOADING", "model loading"),
        ("IDLE", "waiting"),
        ("RECORDING", "key held"),
        ("TRANSCRIBING", "decoding"),
        ("INJECTING", "typing"),
    ]
    x0, nw, gap, ny, nh = 21, 118, 32, 58, 38
    xs = [x0 + i * (nw + gap) for i in range(5)]
    mids = [x + nw / 2 for x in xs]

    # The loop back to IDLE, routed above the spine so it never fights the
    # branch bus below it.
    b.append(
        f'<path class="yz-flow" d="M {mids[4]:g} {ny:g} L {mids[4]:g} 32 L {mids[1]:g} 32 '
        f'L {mids[1]:g} {ny - 2:g}" marker-end="url(#yz-arrow)"/>'
    )
    b.append(text((mids[1] + mids[4]) / 2, 27, "typed — back to idle", "yz-s yz-halo", "middle"))

    for i, (name, sub) in enumerate(spine):
        fit(name, SZ_L, nw - 10, "state")
        fit(sub, SZ_S, nw - 10, "state")
        b.append(f'<g class="yz-node">{tip(f"{name} — {sub}")}')
        b.append(
            f'<rect class="yz-box yz-state" x="{xs[i]:g}" y="{ny:g}" width="{nw:g}" '
            f'height="{nh:g}" rx="7" style="--yz-delay:{i:g}s"/>'
        )
        b.append(text(mids[i], ny + 17, name, "yz-l", "middle"))
        b.append(text(mids[i], ny + 31, sub, "yz-s", "middle"))
        b.append("</g>")
        if i:
            b.append(hline(xs[i] - gap, xs[i] - 2, ny + nh / 2))

    for i, label in enumerate(["model loaded", "key held", "released", "text ready"]):
        cxx = (xs[i] + nw + xs[i + 1]) / 2
        # These sit above the boxes, so they may overhang a node; the real limit
        # is the distance to the next transition label.
        fit(label, SZ_S, nw + gap - 20, "transition label")
        b.append(text(cxx, ny - 6, label, "yz-s yz-halo", "middle"))

    # The two early exits back to IDLE.
    for src, drop, land, label in (
        (mids[2], 116, 250, "silent audio, discarded"),
        (mids[3], 138, 268, "nothing to type"),
    ):
        b.append(
            f'<path class="yz-flow" d="M {src:g} {ny + nh:g} L {src:g} {drop:g} L {land:g} {drop:g} '
            f'L {land:g} {ny + nh + 2:g}" marker-end="url(#yz-arrow)"/>'
        )
        b.append(text((src + land) / 2, drop + 4, label, "yz-s yz-halo", "middle"))

    # Modes: entered deliberately over IPC, never by the hotkey.
    modes = [
        ("MEETING", "yazses meeting start", "Hands-free whole-meeting capture; stopping it finalizes through TRANSCRIBING"),
        ("REMOTE", "SETUP → ACTIVE", "REMOTE_SETUP opens the SSH tunnel, then REMOTE_ACTIVE forwards text to the agent on the other host"),
        ("ENROLLING", "yazses enroll", "The accessibility and microphone calibration wizard"),
        ("READBACK", "speak it back", "Reads a transcript aloud through offline TTS"),
    ]
    mw, mxs = spread(x0, W - 2 * x0, 4, 18)
    mmid = [x + mw / 2 for x in mxs]
    bus_y, my = 162, 180
    b.append(f'<path class="yz-flow" d="M 200 {ny + nh:g} L 200 {bus_y:g}"/>')
    b.append(f'<path class="yz-flow" d="M {mmid[0]:g} {bus_y:g} L {mmid[-1]:g} {bus_y:g}"/>')
    for i, (name, sub, hover) in enumerate(modes):
        b.append(f'<path class="yz-flow" d="M {mmid[i]:g} {bus_y:g} L {mmid[i]:g} {my - 2:g}" marker-end="url(#yz-arrow)"/>')
        b += cell(mxs[i], my, mw, 44, name, sub, hover, "yz-box yz-box--chip", "mode")
    b.append(text(x0, 248, "Modes are entered over IPC, never by the hotkey, and each returns to IDLE when it finishes.", "yz-s"))

    # The two states in the enum that the daemon never sets. A tidier diagram
    # would quietly imply it does.
    gy = 274
    for i, (name, note) in enumerate((("ERROR", "set by the tray"), ("PAUSED", "never set"))):
        gx = x0 + i * 150
        b.append(f'<g class="yz-node">{tip(f"{name} — {note}")}')
        b.append(box(gx, gy, 138, 36, "yz-box yz-box--untimed"))
        b.append(text(gx + 69, gy + 16, name, "yz-l yz-ghost", "middle"))
        b.append(text(gx + 69, gy + 29, note, "yz-s", "middle"))
        b.append("</g>")
    b.append(text(x0 + 316, gy + 14, "In the type, but not states the daemon enters. ERROR is what the tray shows", "yz-s"))
    b.append(text(x0 + 316, gy + 30, "when the daemon stops answering IPC; nothing currently sets PAUSED.", "yz-s"))

    return svg(
        "states",
        326,
        "The daemon state machine",
        "A spine of five states carries ordinary dictation: LOADING to IDLE once the model is "
        "loaded, IDLE to RECORDING when the key is held, RECORDING to TRANSCRIBING when it is "
        "released, TRANSCRIBING to INJECTING when text is ready, and INJECTING back to IDLE. Two "
        "early exits return to IDLE: from RECORDING when the audio was silent, and from "
        "TRANSCRIBING when there was nothing to type. Four further modes hang off IDLE and are "
        "entered over IPC rather than by the hotkey: MEETING, REMOTE_SETUP into REMOTE_ACTIVE, "
        "ENROLLING and READBACK; each returns to IDLE. Two more states exist in the type but are "
        "not entered by the daemon: ERROR is set by the tray when the daemon stops answering, and "
        "nothing currently sets PAUSED.",
        b,
    )


# --------------------------------------------------------------------------- #
# Figure 4 — what is wired and what is designed
# --------------------------------------------------------------------------- #
def fig_capabilities(rows: list[tuple[str, int, int]]) -> str:
    rows = sorted(rows, key=lambda r: r[1] + r[2], reverse=True)
    total = sum(w + p for _n, w, p in rows)
    wired = sum(w for _n, w, _p in rows)

    px, pw = 250, W - 250 - 46
    top, rh, rgap = 84, 24, 11
    axis_max = 35  # a round ceiling just above the largest category
    sc = pw / axis_max
    bottom = top + len(rows) * (rh + rgap) - rgap
    H = bottom + 46
    b: list[str] = []

    # Two series, so a legend is always present — and every segment is also
    # direct-labelled with its count, so identity never rests on hue alone.
    b.append(f'<rect class="yz-swatch yz-bar--ship" x="{px:g}" y="26" width="11" height="11" rx="3"/>')
    b.append(text(px + 18, 36, f"wired and working — {wired}", "yz-l"))
    b.append(f'<rect class="yz-swatch yz-bar--plan" x="{px + 210:g}" y="26" width="11" height="11" rx="3"/>')
    b.append(text(px + 228, 36, f"designed, not wired — {total - wired}", "yz-l"))
    b.append(text(px, 58, f"all {total} capabilities in the registry, by category", "yz-s"))

    # Recessive hairline grid — solid, never dashed.
    for t in range(0, axis_max + 1, 5):
        x = px + t * sc
        b.append(f'<path class="yz-grid" d="M {x:g} {top - 6:g} L {x:g} {bottom + 4:g}"/>')
        b.append(text(x, bottom + 22, str(t), "yz-m", "middle"))
    b.append(text(px + pw / 2, bottom + 40, "capabilities", "yz-m", "middle"))

    for i, (name, w, p) in enumerate(rows):
        y = top + i * (rh + rgap)
        fit(name, SZ_L, px - 14, "capability row label")
        b.append(text(px - 14, y + rh / 2 + 4, name, "yz-l", "end"))
        ww, pwid, delay = w * sc, p * sc, i * 0.06

        b.append(f'<g class="yz-node">{tip(f"{name} — {w} wired and working")}')
        b.append(
            f'<rect class="yz-bar yz-bar--ship" x="{px:g}" y="{y:g}" width="{ww:g}" '
            f'height="{rh:g}" rx="4" style="--yz-delay:{delay:g}s"/>'
        )
        b.append("</g>")
        if p:
            # A 2 px surface gap between the two segments — not a border.
            b.append(f'<g class="yz-node">{tip(f"{name} — {p} designed, not yet wired")}')
            b.append(
                f'<rect class="yz-bar yz-bar--plan" x="{px + ww + 2:g}" y="{y:g}" '
                f'width="{max(pwid - 2, 1):g}" height="{rh:g}" rx="4" style="--yz-delay:{delay:g}s"/>'
            )
            b.append("</g>")

        # Direct labels: inside the segment only when they fit with padding.
        if ww >= 26:
            b.append(text(px + ww - 8, y + rh / 2 + 4, str(w), "yz-v yz-on-ship", "end"))
        else:
            b.append(text(px + ww + 6, y + rh / 2 + 4, str(w), "yz-v"))
        if p:
            if pwid >= 26:
                b.append(text(px + ww + pwid - 8, y + rh / 2 + 4, str(p), "yz-v yz-on-plan", "end"))
            else:
                b.append(text(px + ww + pwid + 6, y + rh / 2 + 4, str(p), "yz-v"))

    return svg(
        "capabilities",
        H,
        "Capabilities by category: wired versus designed",
        f"A stacked bar per category. Of {total} registered capabilities, {wired} are wired and "
        f"working and {total - wired} are designed but not yet wired into the build. "
        + "; ".join(f"{n}: {w} wired, {p} designed" for n, w, p in rows)
        + ".",
        b,
    )


# --------------------------------------------------------------------------- #
# Figure 4 — measured decode latency
# --------------------------------------------------------------------------- #
def fig_latency(bench: dict) -> str:
    models = ["tiny.en", "base.en", "small.en"]
    px, pw = 152, 452
    top, rh, rgap = 78, 32, 26
    bottom = top + len(models) * (rh + rgap) - rgap
    H = bottom + 44
    axis_max = 9000.0
    sc = pw / axis_max
    b: list[str] = []

    b.append(f'<rect class="yz-swatch yz-bar--ship" x="{px:g}" y="24" width="11" height="11" rx="3"/>')
    b.append(text(px + 18, 34, "median decode", "yz-l"))
    b.append(f'<rect class="yz-swatch yz-bar--tail" x="{px + 150:g}" y="24" width="11" height="11" rx="3"/>')
    b.append(text(px + 168, 34, "out to the 95th percentile", "yz-l"))
    b.append(text(px, 56, "one utterance · 30 measured · median audio duration 7.3 s", "yz-s"))

    for t in range(0, 10, 2):
        x = px + t * 1000 * sc
        b.append(f'<path class="yz-grid" d="M {x:g} {top - 6:g} L {x:g} {bottom + 4:g}"/>')
        b.append(text(x, bottom + 20, f"{t} s", "yz-m", "middle"))
    b.append(text(px + pw / 2, bottom + 38, "time from release of the key to text on screen", "yz-m", "middle"))

    for i, name in enumerate(models):
        m = bench["models"][name]
        y = top + i * (rh + rgap)
        med, p95 = m["median_ms"] * sc, m["p95_ms"] * sc
        label = name + (" (default)" if name == "base.en" else "")
        fit(label, SZ_L, px - 14, "latency row label")
        b.append(text(px - 14, y + rh / 2 - 2, label, "yz-l", "end"))
        b.append(text(px - 14, y + rh / 2 + 13, f"cold start {m['cold_s']:.2f} s", "yz-m", "end"))

        b.append('<g class="yz-node">' + tip(f"{name} — 95th percentile {m['p95_ms'] / 1000:.2f} s"))
        b.append(
            f'<rect class="yz-bar yz-bar--tail" x="{px:g}" y="{y:g}" width="{p95:g}" '
            f'height="{rh:g}" rx="4" style="--yz-delay:{i * 0.08:g}s"/>'
        )
        b.append("</g>")
        b.append('<g class="yz-node">' + tip(f"{name} — median {m['median_ms'] / 1000:.2f} s"))
        b.append(
            f'<rect class="yz-bar yz-bar--ship" x="{px:g}" y="{y:g}" width="{med:g}" '
            f'height="{rh:g}" rx="4" style="--yz-delay:{i * 0.08:g}s"/>'
        )
        b.append("</g>")
        b.append(text(px + p95 + 10, y + rh / 2 + 4, f"{m['median_ms'] / 1000:.2f} s median", "yz-v"))

    b.append(text(W - 18, H - 6, bench["machine"], "yz-m", "end"))
    return svg(
        "latency",
        H,
        "Measured decode latency per model",
        "Horizontal bars, median and 95th percentile. "
        + "; ".join(
            f"{n}: median {bench['models'][n]['median_ms'] / 1000:.2f} seconds, "
            f"95th percentile {bench['models'][n]['p95_ms'] / 1000:.2f} seconds, "
            f"cold start {bench['models'][n]['cold_s']:.2f} seconds"
            for n in models
        )
        + ". Accuracy improves down the list while latency worsens, which is the trade-off.",
        b,
    )


# --------------------------------------------------------------------------- #

def fig_direction_triage() -> str:
    """How an idea becomes buildable work, or does not.

    This figure is a *policy*, not a measurement, so unlike the others it derives
    nothing from the benchmark file -- the geometry is the content. It earns a place
    beside them because the policy is the thing that keeps 65 designed-but-unwired
    capabilities from becoming 130: an idea that cannot name the problem it answers
    does not get built, and that gate is invisible in prose.
    """
    b: list[str] = [defs()]
    ny, nh = 176, 74          # gate row
    top, topy = 44, 62        # outcome row (up)
    bot = 330                 # outcome row (down)

    def gate(x: float, w: float, head: str, sub: str, hover: str) -> None:
        b.append(box(x, ny, w, nh, "yz-box"))
        b.append(tip(hover))
        b.append(text(x + w / 2, ny + 28, head, "yz-l", "middle"))
        b.append(text(x + w / 2, ny + 48, sub, "yz-s", "middle"))

    def outcome(x: float, y: float, w: float, head: str, sub: str, cls: str) -> None:
        b.append(box(x, y, w, top, cls))
        b.append(text(x + w / 2, y + 27, head, "yz-l", "middle"))
        b.append(text(x + w / 2, y + 46, sub, "yz-s", "middle"))

    # Entry, then three gates left to right.
    b.append(box(14, ny + 8, 104, 58, "yz-box yz-box--chip"))
    b.append(text(66, ny + 34, "An idea", "yz-l", "middle"))
    b.append(text(66, ny + 52, "from anywhere", "yz-s", "middle"))

    gate(150, 168, "Names a problem?", "problem-space A1-A5, B1-B3",
         "An idea that cannot name the problem it answers is not built. "
         "This is the gate that stops the catalogue growing faster than the evidence.")
    gate(352, 168, "Runs on a laptop?", "offline, CPU only",
         "ADR-011 and ADR-016: no data centre, no new heavy base dependency.")
    gate(554, 192, "Can we tell if it worked?", "a metric, even an expensive one",
         "Without a measurement it is a research question, not a feature.")

    # Outcomes.
    outcome(378, topy, 128, "Needs hardware", "or a lab", "yz-box yz-box--plan")
    outcome(596, topy, 150, "Build now", "ships off by default", "yz-box")
    outcome(596, bot, 150, "Measure first", "a study, not a feature", "yz-box yz-box--untimed")
    outcome(176, bot, 128, "Not built", "no problem, no build", "yz-box yz-box--untimed")

    # Edges: across the gate row, then the branches.
    for x1, x2 in ((118, 146), (318, 348), (520, 550)):
        b.append(f'<path class="yz-flow" d="M {x1} {ny + 37} H {x2}" marker-end="url(#yz-arrow)"/>')
    b.append(text(132, ny + 30, "", "yz-s", "middle"))
    for x, label in ((334, "yes"), (536, "yes")):
        b.append(text(x, ny + 30, label, "yz-s yz-halo", "middle"))

    b.append(f'<path class="yz-flow" d="M 240 {ny + nh} V {bot - 4}" marker-end="url(#yz-arrow)"/>')
    b.append(text(254, 288, "no", "yz-s yz-halo"))
    b.append(f'<path class="yz-flow" d="M 442 {ny} V {topy + top + 4}" marker-end="url(#yz-arrow)"/>')
    b.append(text(456, 156, "no", "yz-s yz-halo"))
    b.append(f'<path class="yz-flow" d="M 671 {ny} V {topy + top + 4}" marker-end="url(#yz-arrow)"/>')
    b.append(text(685, 156, "yes", "yz-s yz-halo"))
    b.append(f'<path class="yz-flow" d="M 671 {ny + nh} V {bot - 4}" marker-end="url(#yz-arrow)"/>')
    b.append(text(685, 288, "no", "yz-s yz-halo"))

    return svg(
        "direction-triage", 420,
        "How a YazSes idea is triaged into buildable, measurable or deferred work",
        "A flowchart with three gates in series. An idea first has to name the problem "
        "it answers from the problem space; if it cannot, it is not built. It then has "
        "to run offline on an ordinary laptop CPU; if it cannot, it is filed as needing "
        "hardware or a lab. Finally it has to have a way of telling whether it worked; "
        "if it does, it is built now, and if it does not, it is a study rather than a "
        "feature.",
        b,
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    bench = read_benchmarks()
    rows = capability_rows()
    total = sum(w + p for _n, w, p in rows)
    wired = sum(w for _n, w, _p in rows)
    n_cmds, n_leaf = command_counts()

    written = {
        "system-map.svg": fig_system_map(total, wired, n_cmds, n_leaf),
        "pipeline-heat.svg": fig_pipeline(bench),
        "states.svg": fig_states(),
        "capabilities.svg": fig_capabilities(rows),
        "latency.svg": fig_latency(bench),
        "direction-triage.svg": fig_direction_triage(),
    }
    for name, content in written.items():
        (OUT / name).write_text(content, encoding="utf-8")
        print(f"wrote docs/assets/arch/{name}  ({len(content):,} bytes)")
    print(f"\n{total} capabilities · {wired} wired · {total - wired} designed")
    print(f"{n_cmds} top-level commands · {n_leaf} counting subcommands")


if __name__ == "__main__":
    main()
