#!/usr/bin/env python3
"""Generate the asciinema terminal cast used in the README and docs (issue #23):

  docs/demo/yazses-cli.cast

Every byte of output in the cast comes from actually running the installed CLI
in-process (``yazses -h``, ``about``, ``quickstart``, ``features``, ``status``) —
nothing here is hand-typed. The one thing a real terminal gives for free that a
plain subprocess capture does not is a tty, which is what both the colour and the
box-drawing panels in ``--help``/``features`` depend on (Rich and Click both check
``isatty()`` and print plain text otherwise). We can't shell out to a real
``asciinema rec`` here — it needs a pty, which the ``fcntl``/``pty`` modules it
depends on don't provide on Windows — so instead we point stdout at a small
wrapper that reports ``isatty() == True``, run each command for real, and record
the resulting bytes with synthetic timing (a short "typed" prompt, then the
output appears, then a pause) into the asciicast v2 format asciinema itself
would have written.

``doctor`` is deliberately left out: its output embeds the machine's real config
and model-cache paths (and already has a dedicated screenshot in the README), and
baking a fresh machine's paths into a committed recording felt like the wrong
tradeoff for this script. ``features`` is long (90+ lines across every category)
so only the first category is kept, with a clearly-marked note in place of the
rest — the note is generated by this script, not app output, and is styled dim so
it doesn't get mistaken for either.

Run:  uv run python scripts/gen-terminal-demo.py
"""
from __future__ import annotations

import io
import json
import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "demo" / "yazses-cli.cast"

COLUMNS = 100
LINES = 30
TITLE = "YazSes — offline hold-to-talk voice dictation"

# (typed command line, argv passed to the Typer app)
COMMANDS: list[tuple[str, list[str]]] = [
    ("yazses -h", ["-h"]),
    ("yazses about", ["about"]),
    ("yazses quickstart", ["quickstart"]),
    ("yazses features", ["features"]),
    ("yazses status", ["status"]),
]

# Categories after this one are cut from the recording — see module docstring.
FEATURES_KEEP_CATEGORIES = 1
FEATURES_TRUNCATION_NOTE = (
    "\x1b[2m… trimmed for the demo — run `yazses features` to see every "
    "category\x1b[0m"
)


class _ForcedTTY:
    """Wraps a text stream so isatty() reports True, so Click/Rich colour and
    box-drawing kick in the way they would in a real terminal. Everything else
    (the bytes written) passes straight through to the real command."""

    def __init__(self, stream: io.TextIOBase) -> None:
        self._stream = stream

    def isatty(self) -> bool:
        return True

    def __getattr__(self, name: str) -> object:
        return getattr(self._stream, name)


def _run(argv: list[str]) -> str:
    """Invoke the real Typer app in-process and return what it printed."""
    from yazses.cli import app

    buf = io.TextIOWrapper(io.BytesIO(), encoding="utf-8", write_through=True)
    real_stdout, real_stderr = sys.stdout, sys.stderr
    sys.stdout = sys.stderr = _ForcedTTY(buf)  # type: ignore[assignment]
    try:
        try:
            app(argv, prog_name="yazses", standalone_mode=False)
        except SystemExit:
            pass
    finally:
        sys.stdout, sys.stderr = real_stdout, real_stderr
    text = buf.buffer.getvalue().decode("utf-8", errors="replace")
    # Normalise line endings to CRLF, which is what a real terminal expects.
    return text.replace("\r\n", "\n").replace("\n", "\r\n")


def _truncate_features(text: str) -> str:
    lines = text.split("\r\n")
    kept: list[str] = []
    category_boundaries = 0
    for line in lines:
        if line.startswith("┌"):  # '┌' — start of a category panel
            category_boundaries += 1
            if category_boundaries > FEATURES_KEEP_CATEGORIES:
                kept.append(FEATURES_TRUNCATION_NOTE)
                break
        kept.append(line)
    return "\r\n".join(kept)


def _type_events(text: str, t: float, *, per_char: float = 0.035) -> tuple[list[list], float]:
    events = []
    for ch in text:
        events.append([round(t, 3), "o", ch])
        t += per_char
    return events, t


def main() -> None:
    os.environ["PYTHONUTF8"] = "1"
    os.environ["NO_COLOR"] = ""  # make sure a leftover NO_COLOR doesn't win

    events: list[list] = [[0.0, "o", "\x1b[?25l"]]  # hide cursor, like a real recording
    t = 0.2

    for i, (typed, argv) in enumerate(COMMANDS):
        prompt_events, t = _type_events(f"$ {typed}", t)
        events.extend(prompt_events)
        events.append([round(t, 3), "o", "\r\n"])
        t += 0.25  # beat for "Enter"

        output = _run(argv)
        if argv == ["features"]:
            output = _truncate_features(output)
        events.append([round(t, 3), "o", output])
        # Output prints effectively instantly in a real terminal too — advance
        # the clock by a nominal amount so the timestamps stay monotonic.
        t += 0.05 + 0.002 * len(output)

        if i < len(COMMANDS) - 1:
            t += 1.0  # pause to read the output before the next command

    events.append([round(t, 3), "o", "\x1b[?25h"])  # show cursor again

    header = {
        "version": 2,
        "width": COLUMNS,
        "height": LINES,
        "timestamp": int(time.time()),
        "idle_time_limit": 2.0,
        "title": TITLE,
        "env": {"TERM": "xterm-256color", "SHELL": "/bin/bash"},
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(header) + "\n")
        for ev in events:
            f.write(json.dumps(ev) + "\n")

    print(f"wrote {OUT.relative_to(ROOT)} ({len(events)} events, ~{t:.1f}s)")


if __name__ == "__main__":
    main()
