#!/usr/bin/env python3
"""Rebuild `design/adr/README.md`'s index from the ADR files themselves.

The index listed **12 of 156** ADRs. It was written when there were eleven, stayed
accurate for one more, and then the corpus grew by an order of magnitude underneath
it. It was not dishonest — a footnote named the other series as a range — but
`adr-v2-001..130` as a single bullet is not an index, and the range had itself gone
stale at 131.

An index maintained by hand against 156 files has one outcome, and this is it. So it
is generated, and `tests/test_adr_index_is_current.py` fails when it drifts — the same
arrangement as `scripts/gen-feature-sizes.py` and `refresh-package-manifests.py`,
for the same reason.

Only the region between the markers is generated. Everything else in that README —
why the v1.0 series is binding, how to supersede an ADR, why the mobile series lives
in `docs/` instead — is prose a generator has no business touching.

    python3 scripts/gen-adr-index.py            # rewrite
    python3 scripts/gen-adr-index.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADR_DIR = ROOT / "design" / "adr"
README = ADR_DIR / "README.md"

BEGIN = "<!-- BEGIN GENERATED ADR INDEX -->"
END = "<!-- END GENERATED ADR INDEX -->"

#: The series, in the order a reader should meet them: the binding v1.0 set first,
#: then the numbered continuation, then the dated v2 programme.
SERIES: tuple[tuple[str, str, str], ...] = (
    ("v1.0 — binding", r"^adr-0\d\d(-|\.)", "Binding for v1.0. Supersede with a new ADR; do not edit in place."),
    ("v0.4 series", r"^adr-v04-", "Decisions from the v0.4 line."),
    ("v2 series", r"^adr-v2-", "The v2 programme: interaction layer, cognitive layer, and everything after."),
)

_TITLE = re.compile(r"^#\s+(.*?)\s*$", re.M)
_STATUS = re.compile(r"^\*\*Status:\*\*\s*(.+?)\s*$", re.M)


def _first(pattern: re.Pattern[str], text: str) -> str:
    m = pattern.search(text)
    return m.group(1).strip() if m else ""


def _short_status(raw: str) -> str:
    """Just the verdict, without the date, wave and commit trailing it.

    A status column of `Accepted (2026-08-15) · implemented in the same change
    (0ddac30)` is a paragraph, and a table of 156 of them is unreadable. The full
    line stays in the ADR, which is where someone reading one decision will look.
    """
    if not raw:
        return "—"
    head = re.split(r"\s*[(·]", raw, maxsplit=1)[0].strip()
    return head or "—"


def _entries() -> list[tuple[str, str, str, str]]:
    """(series, filename, title, status) for every ADR, sorted within its series."""
    out: list[tuple[str, str, str, str]] = []
    seen: set[str] = set()
    for label, pattern, _blurb in SERIES:
        matcher = re.compile(pattern)
        for path in sorted(ADR_DIR.glob("adr-*.md")):
            if not matcher.match(path.name) or path.name in seen:
                continue
            seen.add(path.name)
            text = path.read_text(encoding="utf-8")
            title = _first(_TITLE, text)
            # Strip the redundant "ADR-016 — " prefix; the link already carries it.
            title = re.sub(r"^ADR[-\w.]*\s*[—:-]\s*", "", title).strip()
            out.append((label, path.name, title or path.stem, _short_status(_first(_STATUS, text))))

    unclaimed = sorted(
        p.name for p in ADR_DIR.glob("adr-*.md") if p.name not in seen
    )
    for name in unclaimed:
        text = (ADR_DIR / name).read_text(encoding="utf-8")
        title = re.sub(r"^ADR[-\w.]*\s*[—:-]\s*", "", _first(_TITLE, text)).strip()
        out.append(("Unclassified", name, title or name, _short_status(_first(_STATUS, text))))
    return out


def render() -> str:
    entries = _entries()
    lines = [BEGIN, "", f"*{len(entries)} records. Generated by `scripts/gen-adr-index.py` — do not hand-edit.*", ""]

    blurbs = {label: blurb for label, _p, blurb in SERIES}
    for label in [s[0] for s in SERIES] + ["Unclassified"]:
        rows = [e for e in entries if e[0] == label]
        if not rows:
            continue
        lines += [f"### {label}", ""]
        if blurbs.get(label):
            lines += [blurbs[label], ""]
        lines += ["| ADR | Title | Status |", "|---|---|---|"]
        for _series, name, title, status in rows:
            ident = name[: -len(".md")]
            # Escape pipes: a title containing one would split the row.
            safe = title.replace("|", "\\|")
            lines.append(f"| [{ident}]({name}) | {safe} | {status} |")
        lines.append("")

    lines.append(END)
    return "\n".join(lines)


def apply(text: str, block: str) -> str:
    if BEGIN in text and END in text:
        head = text[: text.index(BEGIN)]
        tail = text[text.index(END) + len(END) :]
        return head + block + tail
    # First run: append, keeping every hand-written word above it.
    return text.rstrip() + "\n\n" + block + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the index is stale")
    args = ap.parse_args(argv)

    current = README.read_text(encoding="utf-8")
    updated = apply(current, render())

    if args.check:
        if current != updated:
            print(
                "design/adr/README.md is out of date. Run:\n"
                "    python3 scripts/gen-adr-index.py",
                file=sys.stderr,
            )
            return 1
        print(f"ADR index is current ({len(_entries())} records).")
        return 0

    README.write_text(updated, encoding="utf-8")
    print(f"Wrote {README.relative_to(ROOT)} — {len(_entries())} records.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
