#!/usr/bin/env python3
"""Generate the Microsoft Store listing artwork from the canonical brand mark.

Why this exists
---------------
`packaging/store/boxart-1080.png` was produced by a cairosvg snippet **pasted into a
README** and regenerated by nothing. That is precisely the shape that let
`snap/gui/yazses.png` drift into being a different logo from every other surface
(fixed in 0e45007) and let `contrib/icons/yazses-*.png` fall behind `render_mark`.
An asset a build script ships and no script redraws is an asset that silently rots.

So the Store art is now generated the same way the icons are: from
``yazses.brandmark.render_mark`` -- the one renderer the tray, the .ico and the .icns
already share -- with **no SVG renderer required**. cairosvg is not installed in the
default environment and is not available on the build hosts, which is the same reason
`gen-icons.py` redraws the geometry in Pillow rather than rasterising the SVG.

What the Store asks for
-----------------------
* **1:1 box art** -- required. 1080x1080.
* **2:3 poster art** -- recommended, and previously *"not made yet"*. 720x1080.

Both are composited on the brand gradient (``BRAND_TOP`` -> ``BRAND_BOTTOM``, the same
stops the terminal banner and the favicon use) so the listing is the same identity as
every other surface rather than a sixth unrelated one.

Usage
-----
    python scripts/gen-store-art.py            # write the assets
    python scripts/gen-store-art.py --check    # verify, write nothing (exit 1 on drift)

``--check`` compares decoded pixels **within a tolerance**, and only over the region that
is deterministic. Three separate things make an exact comparison wrong here:

* PNG bytes are not reproducible -- a different zlib or Pillow build re-encodes identical
  pixels into a different stream. That is what once turned the Windows and macOS release
  legs red on correct assets.
* Decoded *pixels* are not reproducible either. ``render_mark`` supersamples and
  downsamples in floating point, and CI proved the box art -- which contains no text at
  all -- differs on ``ubuntu-24.04-arm`` from the same generator on x86.
* The poster's wordmark is drawn with a **system font**, which differs in version or is
  absent entirely between platforms. So the text region is not compared at all; only the
  mark above it is.

The tolerance itself -- what counts as jitter, what counts as drift, and the measurements
behind both numbers -- lives in ``scripts/imagediff.py``, shared with the icon guards so
the two cannot disagree about what "the same artwork" means.
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from imagediff import explain  # noqa: E402  (needs the sys.path above)

from yazses.branding import BRAND_BOTTOM  # noqa: E402
from yazses.brandmark import render_mark  # noqa: E402

OUT_DIR = ROOT / "packaging" / "store"
BOXART = OUT_DIR / "boxart-1080.png"
POSTER = OUT_DIR / "poster-720x1080.png"

# The Store's own dimensions. Do not "round" these -- Partner Center rejects
# anything that is not exactly the declared aspect.
BOXART_SIZE = (1080, 1080)
POSTER_SIZE = (720, 1080)

# The poster region that is pure geometry. The wordmark and subtitle start below this,
# and they are font-dependent, so they are deliberately outside the comparison.
POSTER_DETERMINISTIC = (0, 0, POSTER_SIZE[0], round(POSTER_SIZE[1] * 0.64))

# The listing sits on white, as the previous box art did and as most Store tiles do.
# The mark carries its own brand-gradient plate, so painting a gradient *behind* it
# would leave a low-contrast frame that reads as a rendering mistake.
BACKGROUND = (255, 255, 255)
INK = BRAND_BOTTOM          # wordmark: the darker brand stop, legible on white
INK_MUTED = (108, 104, 126)  # subtitle: grey with enough contrast for small text

WORDMARK = "YazSes"
# Deliberately shorter than branding.TAGLINE: poster art is read at thumbnail size in
# a grid, where a full sentence is unreadable and reads as noise.
SUBTITLE = "Offline voice dictation"

# Bundled with essentially every Linux distribution and present on the CI runners.
# Falls back to Pillow's bitmap default rather than failing -- art that renders
# slightly plainer is better than a generator that cannot run.
_FONT_CANDIDATES = (
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
)


def _font(px: int) -> ImageFont.ImageFont:
    for path in _FONT_CANDIDATES:
        if Path(path).exists():
            return ImageFont.truetype(path, px)
    return ImageFont.load_default()


def _centre_text(draw: ImageDraw.ImageDraw, cx: int, y: int, text: str, font, fill) -> int:
    left, top, right, bottom = draw.textbbox((0, 0), text, font=font)
    draw.text((cx - (right - left) / 2 - left, y - top), text, font=font, fill=fill)
    return bottom - top


def build_boxart() -> Image.Image:
    """1:1 -- the mark, large, centred. No text: at grid size a wordmark is illegible."""
    img = Image.new("RGB", BOXART_SIZE, BACKGROUND)
    mark_px = round(BOXART_SIZE[0] * 0.72)
    # fill=None is the canonical application icon: brand-gradient plate, white glyph.
    # Anything else would be a sixth variant of the mark, which is the defect 0e45007 fixed.
    mark = render_mark(mark_px)
    img.paste(
        mark,
        ((BOXART_SIZE[0] - mark_px) // 2, (BOXART_SIZE[1] - mark_px) // 2),
        mark,
    )
    return img


def build_poster() -> Image.Image:
    """2:3 -- mark in the upper two-thirds, wordmark and a short subtitle beneath."""
    w, h = POSTER_SIZE
    img = Image.new("RGB", POSTER_SIZE, BACKGROUND)
    mark_px = round(w * 0.62)
    mark = render_mark(mark_px)
    img.paste(mark, ((w - mark_px) // 2, round(h * 0.18)), mark)

    draw = ImageDraw.Draw(img)
    _centre_text(draw, w // 2, round(h * 0.66), WORDMARK, _font(round(w * 0.135)), INK)
    _centre_text(draw, w // 2, round(h * 0.765), SUBTITLE, _font(round(w * 0.052)), INK_MUTED)
    return img


# (path, builder, exact size, region compared by --check or None for the whole image)
TARGETS = (
    (BOXART, build_boxart, BOXART_SIZE, None),
    (POSTER, build_poster, POSTER_SIZE, POSTER_DETERMINISTIC),
)


def check_asset(
    path: Path,
    expected: Image.Image,
    size: tuple[int, int],
    region: tuple[int, int, int, int] | None,
) -> str | None:
    """`None` when the committed file is this generator's output; else why it is not.

    Every failure mode reports drift. A file that is missing, the wrong shape, truncated
    or no longer an image at all is *not* evidence that the artwork is current -- a check
    that cannot parse its input must fail rather than report compliance.
    """
    if not path.exists():
        return "missing"
    try:
        with Image.open(path) as committed:
            committed.load()
            if committed.size != size:
                return f"is {committed.size}, want {size}"
            if region is None:
                return explain(committed, expected)
            return explain(committed.crop(region), expected.crop(region))
    except (OSError, ValueError) as exc:
        return f"unreadable ({type(exc).__name__}: {exc}) -- regenerate it"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; write nothing")
    args = ap.parse_args(argv)

    # A generator with nothing to draw must not report that everything is up to date:
    # every loop below is green over an empty tuple.
    assert TARGETS, "no store assets are declared"

    drift = []
    for path, build, size, region in TARGETS:
        img = build()
        assert img.size == size, f"{path.name}: built {img.size}, want {size}"
        if args.check:
            scope = "" if region is None else " (mark region)"
            reason = check_asset(path, img, size, region)
            if reason is None:
                print(f"{path.relative_to(ROOT)}  ok{scope}")
            else:
                drift.append(f"{path.relative_to(ROOT)}{scope}: {reason}")
            continue
        buf = io.BytesIO()
        img.save(buf, "PNG", optimize=True)
        path.write_bytes(buf.getvalue())
        print(f"{path.relative_to(ROOT)}  {size[0]}x{size[1]}  {len(buf.getvalue()):,} bytes")

    if drift:
        for line in drift:
            print(f"DRIFT: {line}", file=sys.stderr)
        return 1
    if args.check:
        print("store art matches the generator")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
