#!/usr/bin/env python3
"""Generate the reference docs that must never drift from the code:

  docs/features.md        every capability, grouped by category (from features.py)
  docs/configuration.md   every config.toml section + key + default (from config.py)
  docs/command-index.md   every CLI command + options (from the Typer/Click app)

These three are the "reference document for all commands and features". They are
regenerated (never hand-edited) so they stay in lockstep with the registry and the
CLI. Run:  uv run python scripts/gen-docs.py

The prose docs (architecture, roadmap, troubleshooting, how-to) are hand-written
and live alongside these.
"""
from __future__ import annotations

import dataclasses
import io
from pathlib import Path

import click
import typer

from yazses.config import Config
from yazses.system.features import CATEGORY_BLURB, grouped_features
from yazses import branding

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

_TIER_ORDER_NOTE = (
    "**Tiers:** `core` (always on) · `recommended (on by default)` · `recommended` "
    "(safe, worth enabling) · `optional` · `experimental` (rough edges — needs "
    "`--force` to enable)."
)


def _front(title: str, desc: str) -> str:
    return (
        "---\n"
        f"title: {title}\n"
        f"description: {desc}\n"
        "---\n\n"
        f"<!-- GENERATED by scripts/gen-docs.py — do not edit by hand. -->\n\n"
        f"# {title}\n\n"
    )


# --------------------------------------------------------------------------- #
# docs/features.md
# --------------------------------------------------------------------------- #
def gen_features() -> str:
    cfg = Config()
    groups = grouped_features(cfg)
    total = sum(len(f) for _c, _b, f in groups)

    out = io.StringIO()
    out.write(_front("Feature Reference",
                     f"All {total} YazSes capabilities, what each does, and how to turn it on."))
    out.write(
        f"YazSes ships **{total} capabilities**. All but the core are **off by default** — "
        "turn one on with `yazses features enable <toggle>` and apply with `yazses restart`. "
        "Browse them interactively with `yazses features` (grouped) or `yazses features info "
        "<toggle>` (one card).\n\n"
    )
    out.write(_TIER_ORDER_NOTE + "\n\n")

    # table of contents
    out.write("## Contents\n\n")
    for cat, _blurb, feats in groups:
        anchor = cat.lower().replace(" & ", "--").replace(" ", "-").replace(",", "")
        out.write(f"- [{cat}](#{anchor}) ({len(feats)})\n")
    out.write("\n")

    for cat, blurb, feats in groups:
        out.write(f"## {cat}\n\n")
        if blurb:
            out.write(f"*{blurb}*\n\n")
        for f in feats:
            toggle = f.slug if f.toggleable else "—"
            out.write(f"### {f.name}\n\n")
            out.write(f"- **Toggle:** `{toggle}`  ·  **Tier:** {f.tier_label}")
            if f.note:
                out.write(f"  ·  **Config:** `{f.note}`")
            out.write("\n")
            if f.why:
                out.write(f"- **What it does:** {f.why}\n")
            if f.use_case:
                out.write(f"- **Use when:** {f.use_case}\n")
            if f.example:
                out.write(f"- **Example:** {f.example}\n")
            if f.toggleable:
                out.write(
                    f"- **Activate:** `yazses features enable {f.slug}` "
                    "then `yazses restart`\n"
                )
            else:
                out.write("- **Activate:** always on (cannot be disabled)\n")
            out.write("\n")
    return out.getvalue()


# --------------------------------------------------------------------------- #
# docs/configuration.md
# --------------------------------------------------------------------------- #
def _fmt_default(val) -> str:
    if isinstance(val, str):
        return f'`"{val}"`' if val else '`""`'
    if isinstance(val, bool):
        return f"`{str(val).lower()}`"
    if val is None:
        return "`none`"
    if isinstance(val, (list, dict)):
        return f"`{val!r}`"
    return f"`{val}`"


def _type_name(tp) -> str:
    s = getattr(tp, "__name__", str(tp))
    return (
        s.replace("Optional[", "").replace("]", "")
        .replace("typing.", "").replace("str | None", "str?")
    )


def _section_rows(inst) -> list[tuple[str, str, str, str]]:
    """(key, type, default, nested-marker) rows for a dataclass instance, recursing
    one level into nested dataclasses (e.g. filters.disfluency)."""
    rows: list[tuple[str, str, str, str]] = []
    for fld in dataclasses.fields(inst):
        val = getattr(inst, fld.name)
        if dataclasses.is_dataclass(val):
            rows.append((fld.name, "table", "", "nested"))
            for sub in dataclasses.fields(val):
                sv = getattr(val, sub.name)
                rows.append((f"{fld.name}.{sub.name}", _type_name(sub.type),
                             _fmt_default(sv), ""))
        else:
            rows.append((fld.name, _type_name(fld.type), _fmt_default(val), ""))
    return rows


def gen_configuration() -> str:
    cfg = Config()
    out = io.StringIO()
    out.write(_front("Configuration Reference",
                     "Every config.toml section and key, with type and default."))
    cfgdir = "`~/.config/yazses/config.toml`"
    out.write(
        f"YazSes reads its settings from {cfgdir} on Linux "
        "(`~/Library/Application Support/yazses/` on macOS, `%APPDATA%\\yazses\\` on "
        "Windows). **Every section has defaults**, so a missing config file is valid "
        "and every v2 feature is dormant (`enabled = false`) until you opt in.\n\n"
        "Prefer `yazses features enable/disable <toggle>` over hand-editing — it writes "
        "the right keys and preserves your comments. This table is the full surface for "
        "when you do want to edit by hand.\n\n"
    )
    for fld in dataclasses.fields(cfg):
        section = fld.name
        inst = getattr(cfg, section)
        out.write(f"## `[{section}]`\n\n")
        out.write("| Key | Type | Default |\n|---|---|---|\n")
        for key, tp, default, marker in _section_rows(inst):
            if marker == "nested":
                out.write(f"| **`[{section}.{key}]`** | | |\n")
            else:
                out.write(f"| `{key}` | {tp} | {default} |\n")
        out.write("\n")
    return out.getvalue()


# --------------------------------------------------------------------------- #
# docs/command-index.md
# --------------------------------------------------------------------------- #
def _walk_click(cmd: click.Command, name: str, depth: int, out: io.StringIO) -> None:
    prefix = "yazses " + name if name else "yazses"
    heading = "#" * min(depth + 1, 6)
    out.write(f"{heading} `{prefix}`\n\n")
    if cmd.help:
        out.write(cmd.help.strip().split("\n\n")[0].strip() + "\n\n")
    # Typer >=0.13 vendors its own click fork, so isinstance against upstream
    # ``click`` no longer matches. Duck-type on the stable ``param_type_name`` API.
    params = [p for p in cmd.params if p.param_type_name == "option"]
    args = [p for p in cmd.params if p.param_type_name == "argument"]
    if args:
        out.write("- **Arguments:** " + ", ".join(f"`{a.name}`" for a in args) + "\n")
    for opt in params:
        if opt.name in ("help",):
            continue
        flags = ", ".join(f"`{o}`" for o in opt.opts + opt.secondary_opts)
        help_txt = (opt.help or "").strip()
        out.write(f"- {flags} — {help_txt}\n")
    if args or [p for p in params if p.name != "help"]:
        out.write("\n")
    if hasattr(cmd, "commands"):
        for sub_name in sorted(cmd.commands):
            child = cmd.commands[sub_name]
            full = f"{name} {sub_name}".strip()
            _walk_click(child, full, depth + 1, out)


def gen_command_index() -> str:
    from yazses.cli import app

    click_app = typer.main.get_command(app)
    out = io.StringIO()
    out.write(_front("Command Index",
                     "Every yazses CLI command and option, generated from the app."))
    out.write(
        "The complete command tree. For grouped, example-rich help run `yazses --help` "
        "or `yazses <command> --help`. See also the prose "
        "[CLI reference](cli-reference.md).\n\n"
    )
    # top-level commands (Click group)
    assert hasattr(click_app, "commands")
    for sub_name in sorted(click_app.commands):
        _walk_click(click_app.commands[sub_name], sub_name, 1, out)
    return out.getvalue()


def main() -> None:
    DOCS.mkdir(exist_ok=True)
    targets = {
        "features.md": gen_features(),
        "configuration.md": gen_configuration(),
        "command-index.md": gen_command_index(),
    }
    for fname, content in targets.items():
        (DOCS / fname).write_text(content, encoding="utf-8")
        print(f"wrote docs/{fname}  ({content.count(chr(10))} lines)")
    print(f"YazSes {branding.version()} — reference docs regenerated.")


if __name__ == "__main__":
    main()
