#!/usr/bin/env python3
"""Generate the reference docs that must never drift from the code:

  docs/features.md        every capability, grouped by category (from features.py)
  docs/configuration.md   every config.toml section + key + default (from config.py)
  docs/command-index.md   every CLI command + options (from the Typer/Click app)

These three are the "reference document for all commands and features". They are
regenerated (never hand-edited) so they stay in lockstep with the registry and the
CLI. Run:  uv run python scripts/gen-docs.py

The prose docs (architecture, roadmap, troubleshooting, how-to) are hand-written
and live alongside these.
"""
from __future__ import annotations

import ast
import dataclasses
import functools
import io
import sys
from pathlib import Path

import click
import typer

from yazses import branding
from yazses.config import Config
from yazses.system.features import grouped_features

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config_status import inert_dotted_keys  # noqa: E402  (sibling script, not a package)

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

_TIER_ORDER_NOTE = (
    "**Tiers:** `core` (always on) · `recommended (on by default)` · `recommended` "
    "(safe, worth enabling) · `optional` · `experimental` (rough edges — needs "
    "`--force` to enable) · `planned` (designed but not yet wired into this build — "
    "cannot be enabled yet; contributions welcome)."
)



def _download_mb(slug: str):
    """The feature's resolved download size in MB, or None (ADR-018).

    Reads the same committed table the CLI reads, so the feature reference and
    `yazses features info` can never quote different numbers.
    """
    try:
        from yazses.system.depsize import full_download_mb

        return full_download_mb(slug)
    except Exception:
        return None


def _format_mb(mb: float) -> str:
    from yazses.system.depsize import format_mb

    return format_mb(mb)


def _front(title: str, desc: str) -> str:
    return (
        "---\n"
        f"title: {title}\n"
        f"description: {desc}\n"
        "---\n\n"
        f"<!-- GENERATED by scripts/gen-docs.py — do not edit by hand. -->\n\n"
        f"# {title}\n\n"
    )


# --------------------------------------------------------------------------- #
# docs/features.md
# --------------------------------------------------------------------------- #
def gen_features() -> str:
    cfg = Config()
    groups = grouped_features(cfg)
    total = sum(len(f) for _c, _b, f in groups)

    out = io.StringIO()
    out.write(_front("Feature Reference",
                     f"All {total} YazSes capabilities, what each does, and how to turn it on."))
    out.write(
        f"YazSes ships **{total} capabilities**. All but the core are **off by default** — "
        "turn one on with `yazses features enable <toggle>` and apply with `yazses restart`. "
        "Browse them interactively with `yazses features` (grouped) or `yazses features info "
        "<toggle>` (one card).\n\n"
    )
    out.write(_TIER_ORDER_NOTE + "\n\n")

    # table of contents
    out.write("## Contents\n\n")
    for cat, _blurb, feats in groups:
        anchor = cat.lower().replace(" & ", "--").replace(" ", "-").replace(",", "")
        out.write(f"- [{cat}](#{anchor}) ({len(feats)})\n")
    out.write("\n")

    for cat, blurb, feats in groups:
        out.write(f"## {cat}\n\n")
        if blurb:
            out.write(f"*{blurb}*\n\n")
        for f in feats:
            toggle = f.slug if f.toggleable else "—"
            out.write(f"### {f.name}\n\n")
            out.write(f"- **Toggle:** `{toggle}`  ·  **Tier:** {f.tier_label}")
            if f.note:
                out.write(f"  ·  **Config:** `{f.note}`")
            out.write("\n")
            if f.why:
                out.write(f"- **What it does:** {f.why}\n")
            if f.use_case:
                out.write(f"- **Use when:** {f.use_case}\n")
            if f.example:
                out.write(f"- **Example:** {f.example}\n")
            # What it costs to turn on (ADR-018). Only for features that actually
            # fetch something -- a "Download: 0 MB" line on the 126 pure-logic
            # capabilities would be noise, and the absence already says free.
            _mb = _download_mb(f.slug)
            if _mb:
                out.write(f"- **Download:** {_format_mb(_mb)}\n")
            if not f.wired:
                out.write(
                    "- **Activate:** not possible yet — designed but not wired "
                    "into this build (`yazses features enable` refuses it; "
                    "contributions welcome)\n"
                )
            elif f.toggleable:
                out.write(
                    f"- **Activate:** `yazses features enable {f.slug}` "
                    "then `yazses restart`\n"
                )
            else:
                out.write("- **Activate:** always on (cannot be disabled)\n")
            out.write("\n")
    return out.getvalue()


# --------------------------------------------------------------------------- #
# docs/configuration.md
# --------------------------------------------------------------------------- #
def _fmt_default(val) -> str:
    if isinstance(val, str):
        return f'`"{val}"`' if val else '`""`'
    if isinstance(val, bool):
        return f"`{str(val).lower()}`"
    if val is None:
        return "`none`"
    if isinstance(val, (list, dict)):
        return f"`{val!r}`"
    return f"`{val}`"


def _type_name(tp) -> str:
    s = getattr(tp, "__name__", str(tp))
    return (
        s.replace("Optional[", "").replace("]", "")
        .replace("typing.", "").replace("str | None", "str?")
    )


@functools.lru_cache(maxsize=1)
def _field_notes() -> dict[tuple[str, str], str]:
    """`(dataclass name, field name)` -> the trailing `#` comment on its definition.

    The reference table listed 449 keys with a type and a default and no meaning, so
    a key whose *name* misleads had nowhere to say so. `[recimport] max_speakers` is
    the worst of them: on the shipped sherpa backend it becomes
    `FastClusteringConfig(num_clusters=N)`, an **exact** cluster count, so a generous
    "at most 6" invents six people out of three. `config.py` has said exactly that
    beside the field for a long time; the page a user actually reads before editing
    TOML by hand did not.

    Derived from the source rather than a curated list of interesting keys, because a
    curated list is the thing that goes stale: it can only ever describe the traps
    somebody remembered. Anything with a trailing comment gets one, and adding a
    comment is all it takes to document a key.

    Scoped per class, never by bare field name -- `enabled`, `engine` and
    `model_path` each appear in several sections with different meanings, and a
    global name->comment map would print one section's note under another's key.
    """
    src = (ROOT / "src" / "yazses" / "config.py").read_text(encoding="utf-8")
    lines = src.splitlines()
    notes: dict[tuple[str, str], str] = {}
    for node in ast.walk(ast.parse(src)):
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
                continue
            # end_lineno, not lineno: a default spanning several lines carries its
            # comment on the last one.
            idx = (stmt.end_lineno or stmt.lineno) - 1
            comment = _trailing_comment(lines[idx])
            if comment:
                notes[(node.name, stmt.target.id)] = _with_continuations(lines, idx)
            else:
                leading = _leading_block(lines, stmt.lineno - 1)
                if leading:
                    notes[(node.name, stmt.target.id)] = leading
    return notes


def _leading_block(lines: list[str], idx: int) -> str:
    """The comment block written directly above the field at *idx*, at its own indent.

    Trailing comments were the only shape read at first, which left the 56 most
    heavily documented keys in the file with an empty Notes cell -- `[stt] engine`,
    `model`, `language`, `initial_prompt` among them. A key whose explanation runs to
    a paragraph cannot be written after the field, so the keys most worth documenting
    were exactly the ones the reference page said nothing about.

    Indent equality is what makes this safe, and it is the whole guard. A wrapped
    *trailing* comment continues in the column of the `#` that opened it, which is
    always further right than the field indent; a block that belongs to this field
    sits at the field indent. So a continuation can never be mistaken for the next
    field's leading block, and a leading block can never be attached to the field
    above it -- the failure `_with_continuations` was written to avoid.
    """
    if idx <= 0:
        return ""
    indent = len(lines[idx]) - len(lines[idx].lstrip())
    parts: list[str] = []
    j = idx - 1
    while j >= 0:
        line = lines[j]
        stripped = line.strip()
        if not stripped.startswith("#") or (len(line) - len(line.lstrip())) != indent:
            break
        # `#:` is the sphinx attribute-comment spelling and config.py uses it in two
        # sections; publishing the colon puts a stray ": " at the head of the note.
        parts.append(stripped[1:].lstrip(":").strip())
        j -= 1
    return " ".join(p for p in reversed(parts) if p)


def _with_continuations(lines: list[str], idx: int) -> str:
    """The field's trailing comment plus any wrapped remainder on the lines below.

    A comment too long for one line is continued in the same column, and taking only
    the first line silently truncates it -- `[recimport] language` published
    `Whisper code ("en", "fa", …); "" auto-detects;` and dropped the half naming
    `"translate"`, a magic value that then appeared nowhere in the reference at all.

    Alignment is what separates a continuation from the *next* field's leading
    comment, and the difference matters: leading comments are the more common shape
    in this file, and attaching one to the field above would file every note under
    the wrong key. A continuation sits at the trailing comment's own column; a
    leading comment sits at the field indent.
    """
    first = lines[idx]
    col = _comment_column(first)
    parts = [_trailing_comment(first)]
    j = idx + 1
    while j < len(lines):
        nxt = lines[j]
        if not nxt.strip().startswith("#") or nxt.index("#") != col:
            break
        parts.append(nxt.strip()[1:].strip())
        j += 1
    return " ".join(p for p in parts if p)


def _comment_column(line: str) -> int:
    """Index of the `#` that opens *line*'s trailing comment (-1 if there is none)."""
    in_str: str | None = None
    i = 0
    while i < len(line):
        ch = line[i]
        if in_str:
            if ch == "\\":
                i += 2
                continue
            if ch == in_str:
                in_str = None
        elif ch in "\"'":
            in_str = ch
        elif ch == "#":
            return i
        i += 1
    return -1


def _trailing_comment(line: str) -> str:
    """The `# ...` at the end of *line*, or `""` -- ignoring `#` inside a string.

    Naive splitting on `#` would truncate a default like `key: str = "#"` and publish
    the remains as documentation.
    """
    col = _comment_column(line)
    return line[col + 1:].strip() if col >= 0 else ""


def _md_cell(text: str) -> str:
    """Escape a note for a table cell: a bare `|` would end the column early."""
    return text.replace("|", "\\|")


def _section_rows(inst) -> list[tuple[str, str, str, str, str]]:
    """(key, type, default, nested-marker, note) rows for a dataclass instance,
    recursing one level into nested dataclasses (e.g. filters.disfluency)."""
    notes = _field_notes()
    cls = type(inst).__name__
    rows: list[tuple[str, str, str, str, str]] = []
    for fld in dataclasses.fields(inst):
        val = getattr(inst, fld.name)
        if dataclasses.is_dataclass(val):
            rows.append((fld.name, "table", "", "nested", ""))
            sub_cls = type(val).__name__
            for sub in dataclasses.fields(val):
                sv = getattr(val, sub.name)
                rows.append((f"{fld.name}.{sub.name}", _type_name(sub.type),
                             _fmt_default(sv), "", notes.get((sub_cls, sub.name), "")))
        else:
            rows.append((fld.name, _type_name(fld.type), _fmt_default(val), "",
                         notes.get((cls, fld.name), "")))
    return rows


#: Rendered in the Status column of every inert key, and searched for by
#: `tests/test_config_keys_are_read.py` in the committed page. A generated file is
#: only ever compared against its own generator, so `test_gen_docs.py` would stay
#: green if this marking were dropped entirely — the page itself has to be asserted on.
INERT_MARK = "⚠️ inert"


def gen_configuration() -> str:
    cfg = Config()
    inert = inert_dotted_keys(cfg)
    out = io.StringIO()
    out.write(_front("Configuration Reference",
                     "Every config.toml section and key, with type and default."))
    cfgdir = "`~/.config/yazses/config.toml`"
    out.write(
        f"YazSes reads its settings from {cfgdir} on Linux "
        "(`~/Library/Application Support/yazses/` on macOS, `%LOCALAPPDATA%\\yazses\\` on "
        "Windows). **Every section has defaults**, so a missing config file is valid "
        "and every v2 feature is dormant (`enabled = false`) until you opt in.\n\n"
        "Prefer `yazses features enable/disable <toggle>` over hand-editing — it writes "
        "the right keys and preserves your comments. This table is the full surface for "
        "when you do want to edit by hand.\n\n"
        "**Match the Type column exactly.** In TOML only `str` values take quotes; "
        "`int`, `float` and `bool` must be bare. Writing `vad_threshold = \"0.004\"` "
        "instead of `vad_threshold = 0.004` loads without complaint and then fails at "
        "runtime, because the value stays a string where a number is expected. See "
        "[Troubleshooting](troubleshooting.md#dictation-stopped-working-right-after-i-edited-configtoml).\n\n"
    )
    rows_by_section = {
        fld.name: _section_rows(getattr(cfg, fld.name))
        for fld in dataclasses.fields(cfg)
    }
    n_keys = sum(
        1 for rows in rows_by_section.values() for *_, m, _ in rows if m != "nested"
    )
    out.write(
        f"**{len(inert)} of these {n_keys} keys are inert**, and they are marked "
        f"{INERT_MARK} in the Status column. The loader accepts them, `configcheck` "
        "validates them and they have a documented default — but no code reads them, "
        "so setting one loads without complaint and changes nothing. Most belong to "
        "capabilities that are registered but not yet wired; see "
        "[`yazses features`](cli-reference.md) for what is actually switchable. "
        "Both numbers here are counted at generation time, and the list of inert keys "
        "is the same one the test suite gates on, so neither can quietly fall out of "
        "date.\n\n"
        "This has bitten before: `[injection] fallback_to_clipboard` was documented in "
        "seventeen places and defaulted to `true` while nothing read it, so anyone who "
        "turned it off was silently overruled.\n\n"
    )
    for fld in dataclasses.fields(cfg):
        section = fld.name
        out.write(f"## `[{section}]`\n\n")
        out.write("| Key | Type | Default | Status | Notes |\n|---|---|---|---|---|\n")
        for key, tp, default, marker, note in rows_by_section[section]:
            if marker == "nested":
                out.write(f"| **`[{section}.{key}]`** | | | | |\n")
            else:
                status = INERT_MARK if f"{section}.{key}" in inert else ""
                out.write(
                    f"| `{key}` | {tp} | {default} | {status} | {_md_cell(note)} |\n"
                )
        out.write("\n")
    return out.getvalue()


# --------------------------------------------------------------------------- #
# docs/command-index.md
# --------------------------------------------------------------------------- #
def _walk_click(cmd: click.Command, name: str, depth: int, out: io.StringIO) -> None:
    prefix = "yazses " + name if name else "yazses"
    heading = "#" * min(depth + 1, 6)
    out.write(f"{heading} `{prefix}`\n\n")
    if cmd.help:
        out.write(cmd.help.strip().split("\n\n")[0].strip() + "\n\n")
    # Typer >=0.13 vendors its own click fork, so isinstance against upstream
    # ``click`` no longer matches. Duck-type on the stable ``param_type_name`` API.
    params = [p for p in cmd.params if p.param_type_name == "option"]
    args = [p for p in cmd.params if p.param_type_name == "argument"]
    if args:
        out.write("- **Arguments:** " + ", ".join(f"`{a.name}`" for a in args) + "\n")
    for opt in params:
        if opt.name in ("help",):
            continue
        flags = ", ".join(f"`{o}`" for o in opt.opts + opt.secondary_opts)
        help_txt = (opt.help or "").strip()
        out.write(f"- {flags} — {help_txt}\n")
    if args or [p for p in params if p.name != "help"]:
        out.write("\n")
    if hasattr(cmd, "commands"):
        for sub_name in sorted(cmd.commands):
            child = cmd.commands[sub_name]
            full = f"{name} {sub_name}".strip()
            _walk_click(child, full, depth + 1, out)


def gen_command_index() -> str:
    from yazses.cli import app

    click_app = typer.main.get_command(app)
    out = io.StringIO()
    out.write(_front("Command Index",
                     "Every yazses CLI command and option, generated from the app."))
    out.write(
        "The complete command tree. For grouped, example-rich help run `yazses --help` "
        "or `yazses <command> --help`. See also the prose "
        "[CLI reference](cli-reference.md).\n\n"
    )
    # top-level commands (Click group)
    assert hasattr(click_app, "commands")
    for sub_name in sorted(click_app.commands):
        _walk_click(click_app.commands[sub_name], sub_name, 1, out)
    return out.getvalue()


def main() -> None:
    DOCS.mkdir(exist_ok=True)
    targets = {
        "features.md": gen_features(),
        "configuration.md": gen_configuration(),
        "command-index.md": gen_command_index(),
    }
    for fname, content in targets.items():
        (DOCS / fname).write_text(content, encoding="utf-8")
        print(f"wrote docs/{fname}  ({content.count(chr(10))} lines)")
    print(f"YazSes {branding.version()} — reference docs regenerated.")


if __name__ == "__main__":
    main()
