#!/usr/bin/env python3
"""Generate the winget manifest for a released YazSes version.

winget requires the SHA256 of the exact installer it will download, so the
manifest is generated from the published release asset rather than written by
hand — a stale hash fails validation, and a hand-edited one can be wrong in a
way no reviewer will catch.

    python scripts/winget-manifest.py 2.18.0
    python scripts/winget-manifest.py 2.18.0 --out packaging/winget

Then submit by copying the version directory into a winget-pkgs fork under
manifests/m/MSKazemi/YazSes/ and opening a PR. Validate first with:

    winget validate --manifest <dir>
    winget install --manifest <dir>   # installs locally, needs Windows

Requires network access to fetch the asset (~75 MB).
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import urllib.request
from pathlib import Path

PACKAGE_ID = "MSKazemi.YazSes"
REPO = "MSKazemi/yazses"

# Matches the Inno Setup AppId in packaging/windows/installer.iss. Inno appends
# "_is1" to form its uninstall registry key, and winget needs that key to tell
# whether the package is already installed — without it `winget upgrade` cannot
# see an existing install and offers a redundant reinstall forever.
PRODUCT_CODE = "{F3E8B8A4-1B6C-4F24-9BE8-9B7E58E9C4A2}_is1"

# Windows 10 21H2, the floor stated in docs/windows-install.md.
MIN_OS_VERSION = "10.0.19044.0"

SCHEMA = "1.12.0"


def asset_url(version: str) -> str:
    return (
        f"https://github.com/{REPO}/releases/download/"
        f"v{version}/YazSes-{version}-windows-x64.exe"
    )


def sha256_of(url: str) -> str:
    """Stream the asset and hash it without holding 75 MB in memory."""
    digest = hashlib.sha256()
    with urllib.request.urlopen(url) as response:  # noqa: S310 - fixed github.com URL
        if response.status != 200:
            raise SystemExit(f"GET {url} returned {response.status}")
        for chunk in iter(lambda: response.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def version_manifest(version: str) -> str:
    return f"""\
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.{SCHEMA}.schema.json
# Generated by scripts/winget-manifest.py — do not edit by hand.

PackageIdentifier: {PACKAGE_ID}
PackageVersion: {version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: {SCHEMA}
"""


def installer_manifest(version: str, sha256: str) -> str:
    return f"""\
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.{SCHEMA}.schema.json
# Generated by scripts/winget-manifest.py — do not edit by hand.

PackageIdentifier: {PACKAGE_ID}
PackageVersion: {version}
Platform:
- Windows.Desktop
MinimumOSVersion: {MIN_OS_VERSION}
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
ProductCode: '{PRODUCT_CODE}'
ReleaseNotesUrl: https://github.com/{REPO}/releases/tag/v{version}
Installers:
- Architecture: x64
  InstallerUrl: {asset_url(version)}
  InstallerSha256: {sha256}
ManifestType: installer
ManifestVersion: {SCHEMA}
"""


def locale_manifest(version: str) -> str:
    return f"""\
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.{SCHEMA}.schema.json
# Generated by scripts/winget-manifest.py — do not edit by hand.

PackageIdentifier: {PACKAGE_ID}
PackageVersion: {version}
PackageLocale: en-US
Publisher: Mohsen Seyedkazemi Ardebili
PublisherUrl: https://github.com/MSKazemi
PublisherSupportUrl: https://github.com/{REPO}/issues
Author: Mohsen Seyedkazemi Ardebili
PackageName: YazSes
PackageUrl: https://github.com/{REPO}
License: Apache-2.0
LicenseUrl: https://github.com/{REPO}/blob/main/LICENSE
Copyright: Copyright (c) Mohsen Seyedkazemi Ardebili
ShortDescription: Offline hold-to-talk voice dictation that types into any app.
Description: |-
  YazSes is a free, open-source, offline voice dictation and speech-to-text
  daemon. Hold a key, speak, release, and your words are typed into whatever
  application has focus. Transcription runs entirely on-device with
  faster-whisper, so no audio is sent to any cloud service — usable where the
  meeting is confidential, the machine is air-gapped, or a subscription is not
  wanted. Includes editor and terminal voice commands, a personal dictionary,
  and meeting transcription with speaker labels.
Moniker: yazses
Tags:
- accessibility
- dictation
- offline
- privacy
- speech-to-text
- stt
- transcription
- voice
- voice-typing
- whisper
Documentation:
- DocumentLabel: Windows install guide
  DocumentUrl: https://github.com/{REPO}/blob/main/docs/windows-install.md
- DocumentLabel: Documentation site
  DocumentUrl: https://mskazemi.com/yazses/
ManifestType: defaultLocale
ManifestVersion: {SCHEMA}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="Release version without the leading v, e.g. 2.18.0")
    parser.add_argument(
        "--out",
        default="packaging/winget",
        help="Directory to write the version folder into (default: packaging/winget)",
    )
    parser.add_argument(
        "--sha256",
        help="Skip the download and use this hash (uppercase hex). For testing.",
    )
    args = parser.parse_args()

    version = args.version.lstrip("v")
    url = asset_url(version)

    if args.sha256:
        sha = args.sha256.upper()
    else:
        print(f"Hashing {url} ...", file=sys.stderr)
        sha = sha256_of(url)
    print(f"SHA256 {sha}", file=sys.stderr)

    out = Path(args.out) / version
    out.mkdir(parents=True, exist_ok=True)

    written = {
        f"{PACKAGE_ID}.yaml": version_manifest(version),
        f"{PACKAGE_ID}.installer.yaml": installer_manifest(version, sha),
        f"{PACKAGE_ID}.locale.en-US.yaml": locale_manifest(version),
    }
    for name, body in written.items():
        (out / name).write_text(body, encoding="utf-8")
        print(f"wrote {out / name}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
