"""What enabling a feature will actually download (ADR-018).

`yazses features enable voiceprint` resolves `speechbrain` to torch and the whole
NVIDIA CUDA stack -- on a CPU-only, offline dictation tool. Nothing told the user
that before the download started. This module supplies the number.

Three properties it has to have, and each one rules out an easier design:

**It is the marginal cost, not the feature's total.** The `tts`, `silero` and
`parakeet` extras each name an `onnxruntime` that a base install already has, because
`faster-whisper` depends on it. Quoting a feature's whole closure would bill the user
53 MB they will not download. So the figure is computed against what is *missing on
this machine*, which `deps.missing_modules` already answers.

**It is offline and instant.** The catalogue lists 144 capabilities and must render
with no network (ADR-011) and no perceptible delay. Sizes therefore come from a table
generated by `scripts/gen-feature-sizes.py` and committed, never from a live query. A
stale number is acceptable; a hang or an outbound connection is not.

**It says "unknown" rather than guessing.** A feature whose size is absent from the
table reports nothing at all. Showing a confident wrong number is worse than showing
none -- especially downward, which is the direction that would matter here.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_TABLE_PATH = Path(__file__).with_name("feature_sizes.json")

#: Above this, `features enable` says so prominently rather than in passing. Set
#: where it is because the failure being prevented is "I asked for a small feature
#: and it filled my disk" -- a few hundred MB on a laptop is a decision, not a detail.
LOUD_DOWNLOAD_MB = 250.0


@lru_cache(maxsize=1)
def _table() -> dict[str, dict]:
    """The committed size table, or an empty one if it is absent or unreadable.

    Never raises. A missing table degrades the catalogue to what it showed before
    sizes existed, which is a cosmetic loss; an exception here would break
    `yazses features` entirely, which is not.
    """
    try:
        return json.loads(_TABLE_PATH.read_text(encoding="utf-8")).get("features", {})
    except (OSError, ValueError):
        return {}


def full_download_mb(slug: str) -> float | None:
    """Download size of *slug*'s whole dependency closure, or ``None`` if unknown.

    This is the figure for a machine that has none of it yet -- what the catalogue
    shows, since the catalogue is not per-machine.
    """
    entry = _table().get(slug)
    if not entry:
        return None
    mb = entry.get("download_mb")
    return float(mb) if isinstance(mb, (int, float)) else None


def distribution_count(slug: str) -> int | None:
    """How many distributions *slug* resolves to, or ``None`` if unknown."""
    entry = _table().get(slug)
    if not entry:
        return None
    n = entry.get("packages")
    return int(n) if isinstance(n, int) else None


def marginal_download_mb(slug: str, missing: list[str] | tuple[str, ...] | None) -> float | None:
    """What enabling *slug* costs **on this machine**, or ``None`` if unknown.

    *missing* is the feature's absent import names, as returned by
    `deps.missing_modules`. Two cases are exact and one is deliberately coarse:

    * ``missing`` empty -> **0.0**. Everything is already installed; enabling is free.
      This is a real case (`stt-moonshine` on a dev install) and worth saying plainly.
    * ``missing`` is the feature's full set -> the whole closure size.
    * ``missing`` is a strict subset -> the closure size is an **over**-estimate, and
      it is returned as such rather than apportioned.

    That last choice is deliberate. Apportioning would need per-distribution
    attribution the table does not carry, and any split would be a guess. Over-quoting
    is the safe direction: a user who is told "up to 120 MB" and downloads 40 is
    mildly surprised; one told 40 who downloads 2 GB has been misled about the only
    thing they asked.
    """
    if missing is not None and len(missing) == 0:
        return 0.0
    return full_download_mb(slug)


def format_mb(mb: float | None) -> str:
    """Render a size for a terminal, or ``""`` when it is unknown.

    Unknown renders as the empty string so callers can concatenate without having to
    special-case it, and so nothing is claimed when nothing is known.
    """
    if mb is None:
        return ""
    if mb == 0:
        return "already installed"
    if mb >= 1000:
        return f"~{mb / 1000:.1f} GB"
    if mb >= 10:
        return f"~{mb:.0f} MB"
    return f"~{mb:.1f} MB"


def download_note(slug: str, missing: list[str] | tuple[str, ...] | None) -> str:
    """One line for the user about what enabling *slug* will fetch, or ``""``.

    Empty when the feature needs nothing, or when the size is unknown -- in both
    cases there is nothing honest to say.
    """
    mb = marginal_download_mb(slug, missing)
    if mb is None or mb == 0:
        return ""
    count = distribution_count(slug)
    approx = "up to " if missing and count and len(missing) < count else ""
    packages = f" ({count} packages)" if count else ""
    return f"downloads {approx}{format_mb(mb)}{packages}"


def is_a_large_download(slug: str, missing: list[str] | tuple[str, ...] | None) -> bool:
    """Whether enabling *slug* deserves more than a passing mention."""
    mb = marginal_download_mb(slug, missing)
    return mb is not None and mb >= LOUD_DOWNLOAD_MB
