"""What enabling a feature will actually download (ADR-018).

`yazses features enable voiceprint` resolves `speechbrain` to torch and the whole
NVIDIA CUDA stack -- on a CPU-only, offline dictation tool. Nothing told the user
that before the download started. This module supplies the number.

Three properties it has to have, and each one rules out an easier design:

**It is the marginal cost, not the feature's total.** The `tts`, `silero` and
`parakeet` extras each name an `onnxruntime` that a base install already has, because
`faster-whisper` depends on it. Quoting a feature's whole closure would bill the user
53 MB they will not download. So the figure is computed against what is *missing on
this machine*, which `deps.missing_modules` already answers.

**It is offline and instant.** The catalogue lists 144 capabilities and must render
with no network (ADR-011) and no perceptible delay. Sizes therefore come from a table
generated by `scripts/gen-feature-sizes.py` and committed, never from a live query. A
stale number is acceptable; a hang or an outbound connection is not.

**It says "unknown" rather than guessing.** A feature whose size is absent from the
table reports nothing at all. Showing a confident wrong number is worse than showing
none -- especially downward, which is the direction that would matter here.

**It counts model files, which pip never sees.** The table is generated by resolving
pip closures, so for a while the catalogue priced `read-back` at 12 MB while
`tts/download.py`'s own docstring said the Kokoro voice it fetches on first run is
**340 MB**. Both numbers were written down in this repository; nothing compared them,
so the feature that most deserved `LOUD_DOWNLOAD_MB` -- "I asked for a small feature
and it filled my disk" -- was the one that could never trip it. `_MODEL_FETCHERS` is
that comparison, and `tests/test_feature_size_counts_model_files.py` derives both
sides of it from the tree so a fifth downloader cannot ship unpriced.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_TABLE_PATH = Path(__file__).with_name("feature_sizes.json")

#: Above this, `features enable` says so prominently rather than in passing. Set
#: where it is because the failure being prevented is "I asked for a small feature
#: and it filled my disk" -- a few hundred MB on a laptop is a decision, not a detail.
LOUD_DOWNLOAD_MB = 250.0


#: Every module in the tree that fetches model files, the megabytes it fetches, and
#: the feature slugs that pay for it. Keyed by the module so the guard can hold this
#: against the tree itself rather than against a list someone remembered to extend.
#:
#: `stt/download.py` maps to no slug on purpose: it fetches the base Whisper
#: checkpoint, which is not a capability anyone toggles and whose size is whatever
#: `[stt] model` names.
#:
#: The first version of this map was keyed on files **named** `download.py`, and that
#: was the defect rather than an implementation detail of it. The two alternative STT
#: engines fetch their weights through their own library at first use --
#: `onnx_asr.load_model` and `MoonshineOnnxModel(...)` -- so neither owns a
#: `download.py`, and both were priced at their wheel alone: `stt-parakeet` advertised
#: **~4.0 MB** in `yazses features` while `docs/models.md` said "~600 MB model" two
#: tables away. The repo already held the complete classification, in
#: `tests/test_model_cache_first.py::_LOADERS` -- which names `stt/parakeet.py` -- and
#: nothing compared the two lists. `tests/test_feature_size_counts_model_files.py`
#: now does.
#:
#: A ``None`` size means *this fetches a model and we have not established how big*.
#: It is deliberately distinct from ``0.0``: unknown must never be added to a total
#: (that would invent a number), but it must still be said out loud, because saying
#: "113 MB" about something that then downloads a speech model is the failure this
#: whole module exists to prevent.
_MODEL_FETCHERS: dict[str, tuple[float | None, tuple[str, ...]]] = {
    "yazses/tts/download.py": (340.0, ("read-back", "readback_clone")),
    "yazses/recimport/download.py": (45.0, ("recimport", "meeting", "diarize")),
    "yazses/gaze/download.py": (3.7, ("gaze",)),
    "yazses/stt/download.py": (0.0, ()),
    # Sourced from `docs/models.md`, which has said "~600 MB model" since the engine
    # shipped; the guard holds the two equal so they cannot drift apart again.
    "yazses/stt/parakeet.py": (600.0, ("stt-parakeet",)),
    # `moonshine/base` through `moonshine_onnx`. No figure for it exists anywhere in
    # this repo and one is not being invented here -- see the ``None`` note above.
    "yazses/stt/moonshine.py": (None, ("stt-moonshine",)),
    # speechbrain ECAPA, fetched by `from_hparams` when a voiceprint is enrolled.
    # `cocktail` is the only toggle that needs one. The figure is the module's own
    # ("Apache-2.0, ~20 MB, CPU-runnable"), which the guard holds it to.
    "yazses/voiceprint/ecapa.py": (20.0, ("cocktail",)),
    # pyannote maps to no slug for the same reason as `stt/download.py`: it is chosen
    # by `[recimport] backend = "pyannote"`, a config value rather than a capability,
    # so no `features enable` ever prices it. (The adapter itself does ship, behind
    # the `diarization-pyannote` extra -- an earlier version of this comment said
    # otherwise, citing `system/backends.py`, which says the opposite.) The sherpa
    # models that the default path fetches are priced above.
    "yazses/recimport/pyannote_backend.py": (None, ()),
}

_MODEL_MB: dict[str, float | None] = {
    slug: mb for mb, slugs in _MODEL_FETCHERS.values() for slug in slugs
}


@lru_cache(maxsize=1)
def _table() -> dict[str, dict]:
    """The committed size table, or an empty one if it is absent or unreadable.

    Never raises. A missing table degrades the catalogue to what it showed before
    sizes existed, which is a cosmetic loss; an exception here would break
    `yazses features` entirely, which is not.
    """
    try:
        return json.loads(_TABLE_PATH.read_text(encoding="utf-8")).get("features", {})
    except (OSError, ValueError):
        return {}


def full_download_mb(slug: str) -> float | None:
    """Download size of *slug*'s whole dependency closure, or ``None`` if unknown.

    This is the figure for a machine that has none of it yet -- what the catalogue
    shows, since the catalogue is not per-machine.
    """
    entry = _table().get(slug)
    if not entry:
        return None
    mb = entry.get("download_mb")
    return float(mb) if isinstance(mb, (int, float)) else None


def distribution_count(slug: str) -> int | None:
    """How many distributions *slug* resolves to, or ``None`` if unknown."""
    entry = _table().get(slug)
    if not entry:
        return None
    n = entry.get("packages")
    return int(n) if isinstance(n, int) else None


def marginal_download_mb(slug: str, missing: list[str] | tuple[str, ...] | None) -> float | None:
    """What enabling *slug* costs **on this machine**, or ``None`` if unknown.

    *missing* is the feature's absent import names, as returned by
    `deps.missing_modules`. Two cases are exact and one is deliberately coarse:

    * ``missing`` empty -> **0.0**. Everything is already installed; enabling is free.
      This is a real case (`stt-moonshine` on a dev install) and worth saying plainly.
    * ``missing`` is the feature's full set -> the whole closure size.
    * ``missing`` is a strict subset -> the closure size is an **over**-estimate, and
      it is returned as such rather than apportioned.

    That last choice is deliberate. Apportioning would need per-distribution
    attribution the table does not carry, and any split would be a guess. Over-quoting
    is the safe direction: a user who is told "up to 120 MB" and downloads 40 is
    mildly surprised; one told 40 who downloads 2 GB has been misled about the only
    thing they asked.
    """
    if missing is not None and len(missing) == 0:
        return 0.0
    return full_download_mb(slug)


def model_download_mb(slug: str) -> float:
    """Model files *slug* fetches the first time it runs, in MB; ``0.0`` if none.

    Not part of `full_download_mb`, which answers a question about pip. These arrive
    later and from somewhere else -- a GitHub release asset, a Google-hosted bundle --
    and they are the larger half for every feature that has them.

    Unlike the pip figure this one is not marginal: whether the file is already on
    disk is a per-machine fact that only the feature's own downloader knows, and
    over-quoting is the safe direction (see `marginal_download_mb`).
    """
    return _MODEL_MB.get(slug) or 0.0


def fetches_a_model(slug: str) -> bool:
    """Whether *slug* downloads model files at all, size established or not.

    Separate from `model_download_mb` because the two answer different questions and
    only one of them can be added up. A feature whose model size is unknown returns
    ``0.0`` there -- inventing a number would be worse than any silence -- and ``True``
    here, which is what lets every caller still say that a download is coming.
    """
    return slug in _MODEL_MB and _MODEL_MB[slug] != 0.0


def first_use_mb(slug: str) -> float | None:
    """Everything a fresh machine downloads to use *slug* -- packages **and** models.

    ``None`` only when the packages are unknown *and* there are no model files, which
    is the one case where nothing can honestly be said.
    """
    packages = full_download_mb(slug)
    model = model_download_mb(slug)
    if packages is None:
        return model or None
    return packages + model


def format_mb(mb: float | None) -> str:
    """Render a size for a terminal, or ``""`` when it is unknown.

    Unknown renders as the empty string so callers can concatenate without having to
    special-case it, and so nothing is claimed when nothing is known.
    """
    if mb is None:
        return ""
    if mb == 0:
        return "already installed"
    if mb >= 1000:
        return f"~{mb / 1000:.1f} GB"
    if mb >= 10:
        return f"~{mb:.0f} MB"
    return f"~{mb:.1f} MB"


#: Width the catalogue pads the size column to. `~3.1 GB` is the longest real
#: label; ADVICE follows it, so an overflow would shift a whole column.
SIZE_COLUMN_WIDTH = 9


def catalogue_size_label(slug: str, has_pip_deps: bool) -> str:
    """The size shown beside *slug* in `yazses features`, or ``""``.

    Deliberately the **whole** closure rather than the marginal figure
    `download_note` quotes. The catalogue is a reference table read by someone
    deciding what to turn on, and it is not per-machine: quoting this machine's
    remainder would advertise a 3 GB feature as free to every reader of a dev box
    that happens to already have torch. `features enable` still quotes the
    marginal cost, because that one is a bill, not a price list.

    It is also the only figure that can be produced instantly -- the marginal one
    needs `deps.missing_modules`, which imports each feature's modules, and the
    catalogue has 144 rows to render with no perceptible delay (ADR-018).

    Model files are included, because the column is read as the price of the row
    and the reader has no way to know a second download follows the first.

    Empty for a feature that downloads nothing, that is absent from the table, or
    whose size is zero -- `format_mb(0)` says "already installed", which is a
    claim about a machine and this function is not looking at one.
    """
    mb = (full_download_mb(slug) or 0.0) if has_pip_deps else 0.0
    mb += model_download_mb(slug)
    # A model whose size is not established still has to appear, or the column reads
    # as the whole price of the row when it is only the wheel. `+` rather than a
    # guessed number: the reader can see there is more without being told how much.
    unquantified = fetches_a_model(slug) and not model_download_mb(slug)
    if not mb:
        return "~?" if unquantified else ""
    return format_mb(mb) + ("+" if unquantified else "")


def download_note(slug: str, missing: list[str] | tuple[str, ...] | None) -> str:
    """One line for the user about what enabling *slug* will fetch, or ``""``.

    Model files are named as their own clause rather than folded into the total,
    because they arrive at a different time: the packages land while the user waits
    on `features enable`, the model on the first run afterwards. A single number
    would be right about the disk and wrong about when the wait happens.

    They are also quoted even when every package is already installed -- that is the
    case where the old early return said "downloads nothing" to someone about to
    fetch 340 MB.

    Empty when the feature needs nothing, or when the size is unknown -- in both
    cases there is nothing honest to say.
    """
    mb = marginal_download_mb(slug, missing)
    model = model_download_mb(slug)
    parts = []
    if mb:
        count = distribution_count(slug)
        approx = "up to " if missing and count and len(missing) < count else ""
        packages = f" ({count} package{'' if count == 1 else 's'})" if count else ""
        parts.append(f"downloads {approx}{format_mb(mb)}{packages}")
    if model:
        lead = "plus" if parts else "downloads"
        parts.append(f"{lead} {format_mb(model)} of model files on first use")
    elif fetches_a_model(slug):
        lead = "plus" if parts else "downloads"
        parts.append(f"{lead} a speech model on first use (size depends on the model)")
    return ", ".join(parts)


def is_a_large_download(slug: str, missing: list[str] | tuple[str, ...] | None) -> bool:
    """Whether enabling *slug* deserves more than a passing mention.

    Judged on packages **and** model files together, since the disk does not
    distinguish them. `read-back` is the case that forced it: 12 MB of packages and
    340 MB of voice, quietly under the threshold on the only number anyone checked.

    A feature whose model size is *unknown* is always loud. That is a policy choice and
    it is the defensible one: the alternative is to weigh an unweighable download as
    zero, which is how `stt-parakeet` came to advertise 4.0 MB.
    """
    mb = marginal_download_mb(slug, missing) or 0.0
    if fetches_a_model(slug) and not model_download_mb(slug):
        # An unquantified model download is exactly the risk this threshold exists for
        # -- "I asked for a small feature and it filled my disk" -- and the one thing
        # that cannot be done about it is to weigh it. Over-quoting is the safe
        # direction, as `marginal_download_mb` argues for the same reason.
        return True
    return (mb + model_download_mb(slug)) >= LOUD_DOWNLOAD_MB
