# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: MSKazemi.YazSes
PackageVersion: 2.28.0
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ProductCode: '{F3E8B8A4-1B6C-4F24-9BE8-9B7E58E9C4A2}_is1'
MinimumOSVersion: 10.0.19041.0
ReleaseDate: 2026-08-18
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/MSKazemi/yazses/releases/download/v2.28.0/YazSes-2.28.0-windows-x64.exe
    InstallerSha256: 2E3FB08734D5CEB4454FFC5CE2A93261050C1B65D91DAD6BEEEAE45D7525269D
ManifestType: installer
ManifestVersion: 1.6.0
